import crypto from "node:crypto";
import http from "node:http";
import { URL } from "node:url";
import pg from "pg";
import { generateCertificatePdf, generateSignedPdf } from "./pdf.mjs";

const { Pool } = pg;

const ENVELOPE_PREFIX = process.env.ENVELOPE_PREFIX || "OM";
const FRONTEND_ORIGIN = process.env.FRONTEND_ORIGIN || "*";

let pool = null;

function sanitizeDatabaseUrl(raw) {
  if (!raw) return "";
  let url = raw.trim();
  if (!url) return "";
  url = url.replace(/[?&]channel_binding=[^&]*/gi, "");
  url = url.replace(/\?$/, "").replace(/&$/, "");
  if (process.env.NODE_ENV === "production" && !/sslmode=/i.test(url)) {
    const sep = url.includes("?") ? "&" : "?";
    url = `${url}${sep}sslmode=require`;
  }
  return url;
}

async function initDbPool() {
  const connStr = sanitizeDatabaseUrl(process.env.DATABASE_URL || "");
  if (!connStr) {
    console.warn("DATABASE_URL not set; database operations will fail at runtime");
    return;
  }
  pool = new Pool({
    connectionString: connStr,
    ssl: process.env.NODE_ENV === "production" ? { rejectUnauthorized: false } : false,
  });
  try {
    const client = await pool.connect();
    try {
      await client.query("select 1");
    } finally {
      client.release();
    }
    console.log("neon database connection ok");
  } catch (err) {
    console.error("neon database connection failed:", err.message);
    throw err;
  }
}

async function initDb() {
  if (!pool) return;
  await pool.query("create extension if not exists pgcrypto");
  await pool.query(`
    create table if not exists envelopes (
      id bigint generated by default as identity primary key,
      envelope_id text unique not null,
      status text,
      created_at timestamptz,
      viewed_at timestamptz,
      signed_at timestamptz,
      ip_address text,
      user_agent text,
      viewed_ip text,
      viewed_user_agent text,
      signed_ip text,
      signed_user_agent text,
      pdf_hash text,
      pdf_path text,
      certificate_path text,
      pdf_bytes bytea,
      certificate_bytes bytea,
      occu_med_rep_name text,
      occu_med_rep_title text,
      clinic_rep_name text,
      clinic_rep_title text,
      agreed_electronic boolean,
      recipient_email text,
      payload jsonb,
      updated_at timestamptz not null default now()
    );
  `);
  console.log("database initialized");
}

function newEnvelopeId() {
  const rand = crypto.randomBytes(8).toString("hex").toUpperCase();
  return `${ENVELOPE_PREFIX}-${Date.now().toString(36).toUpperCase()}-${rand}`;
}

function sha256Hex(bytes) {
  return crypto.createHash("sha256").update(bytes).digest("hex");
}

function base64ToUint8(base64) {
  return Uint8Array.from(Buffer.from(base64, "base64"));
}

function getClientIp(req) {
  const fwd = req.headers["x-forwarded-for"];
  if (typeof fwd === "string" && fwd.length > 0) return fwd.split(",")[0].trim();
  return req.socket.remoteAddress || "unknown";
}

function sendJson(res, status, body) {
  res.writeHead(status, {
    "Content-Type": "application/json",
    "Access-Control-Allow-Origin": FRONTEND_ORIGIN,
    "Access-Control-Allow-Headers": "Content-Type",
    "Access-Control-Allow-Methods": "GET,POST,OPTIONS",
  });
  res.end(JSON.stringify(body));
}

function readJson(req) {
  return new Promise((resolve, reject) => {
    let raw = "";
    req.on("data", (chunk) => {
      raw += chunk;
      if (raw.length > 12_000_000) {
        reject(new Error("Payload too large"));
        req.destroy();
      }
    });
    req.on("end", () => {
      try {
        resolve(raw ? JSON.parse(raw) : {});
      } catch (e) {
        reject(e);
      }
    });
    req.on("error", reject);
  });
}


async function maybeSendEmail({ to, envelopeId, pdfHash, pdfBytes, certBytes }) {
  const apiKey = process.env.RESEND_API_KEY;
  const from = process.env.MAIL_FROM;
  if (!to || !apiKey || !from) return;

  await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from,
      to,
      subject: `Signed Clinic Memo ${envelopeId}`,
      text: `Envelope ${envelopeId} has been finalized.\nSHA-256: ${pdfHash}`,
      attachments: [
        { filename: `${envelopeId}-signed.pdf`, content: Buffer.from(pdfBytes).toString("base64") },
        { filename: `${envelopeId}-certificate.pdf`, content: Buffer.from(certBytes).toString("base64") },
      ],
    }),
  });
}

async function sendMemoEmail({ to, subject, text, pdfBytes, filename }) {
  const apiKey = process.env.RESEND_API_KEY;
  const from = process.env.MAIL_FROM;
  if (!to || !apiKey || !from) {
    throw new Error("Email provider not configured");
  }

  const response = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from,
      to,
      subject,
      text,
      attachments: [
        { filename, content: Buffer.from(pdfBytes).toString("base64") },
      ],
    }),
  });

  if (!response.ok) {
    const details = await response.text();
    throw new Error(`Resend send failed (${response.status}): ${details}`);
  }
}

async function getEnvelope(envelopeId) {
  const { rows } = await pool.query(
    "select envelope_id, created_at, viewed_at from envelopes where envelope_id = $1",
    [envelopeId]
  );
  return rows.length > 0 ? rows[0] : null;
}

const server = http.createServer(async (req, res) => {
  if (req.method === "OPTIONS") {
    res.writeHead(204, {
      "Access-Control-Allow-Origin": FRONTEND_ORIGIN,
      "Access-Control-Allow-Headers": "Content-Type",
      "Access-Control-Allow-Methods": "GET,POST,OPTIONS",
    });
    return res.end();
  }

  const url = new URL(req.url || "/", `http://${req.headers.host}`);

  try {
    if (req.method === "GET" && url.pathname === "/health") {
      return sendJson(res, 200, { ok: true, service: "occu-med-backend", timestamp: new Date().toISOString() });
    }

    if (req.method === "POST" && url.pathname === "/api/signed/envelopes") {
      const envelopeId = newEnvelopeId();
      const createdAt = new Date().toISOString();
      const ip = getClientIp(req);
      const userAgent = req.headers["user-agent"] || "unknown";

      await pool.query(
        "insert into envelopes (envelope_id, created_at, ip_address, user_agent, status) values ($1, $2, $3, $4, $5)",
        [envelopeId, createdAt, ip, userAgent, "created"]
      );

      return sendJson(res, 200, { envelopeId, createdAt });
    }

    const viewMatch = url.pathname.match(/^\/api\/signed\/envelopes\/([^/]+)\/view$/);
    if (req.method === "POST" && viewMatch) {
      const envelopeId = decodeURIComponent(viewMatch[1]);
      const viewedAt = new Date().toISOString();
      const ip = getClientIp(req);
      const ua = req.headers["user-agent"] || "unknown";

      await pool.query(
        `insert into envelopes (envelope_id, viewed_at, viewed_ip, viewed_user_agent, status, created_at, updated_at)
         values ($1, $2, $3, $4, $5, $2, now())
         on conflict (envelope_id) do update set
           viewed_at = excluded.viewed_at,
           viewed_ip = excluded.viewed_ip,
           viewed_user_agent = excluded.viewed_user_agent,
           status = excluded.status,
           updated_at = now()`,
        [envelopeId, viewedAt, ip, ua, "viewed"]
      );

      return sendJson(res, 200, { envelopeId, viewedAt });
    }

    const finalizeMatch = url.pathname.match(/^\/api\/signed\/envelopes\/([^/]+)\/finalize$/);
    if (req.method === "POST" && finalizeMatch) {
      const envelopeId = decodeURIComponent(finalizeMatch[1]);
      const body = await readJson(req);
      const { data, viewedAt, recipientEmail } = body;

      if (!data?.agreedElectronic) return sendJson(res, 400, { error: "Agreement required." });
      if (!data?.occuMedRepName || !data?.clinicRepFullName) {
        return sendJson(res, 400, { error: "Both signatures are required." });
      }

      const signedAt = new Date().toISOString();
      const existingEnvelope = await getEnvelope(envelopeId);
      const createdAt = existingEnvelope?.created_at || signedAt;
      const effectiveViewedAt = viewedAt || existingEnvelope?.viewed_at || signedAt;
      const ip = getClientIp(req);
      const userAgent = req.headers["user-agent"] || "unknown";

      const pdfBytes = data?.signedPdfBase64
        ? base64ToUint8(data.signedPdfBase64)
        : await generateSignedPdf({ envelopeId, data, signedAt, viewedAt: effectiveViewedAt, ip, userAgent });

      const pdfHash = sha256Hex(pdfBytes);
      const certBytes = await generateCertificatePdf({
        envelopeId,
        pdfHash,
        audit: {
          createdAt,
          viewedAt: effectiveViewedAt,
          signedAt,
          ipAddress: ip,
          userAgent,
          occuMedRepName: data.occuMedRepName,
          clinicRepFullName: data.clinicRepFullName,
          agreedElectronic: Boolean(data.agreedElectronic),
        },
      });

      const pdfPath = `${envelopeId}/document.pdf`;
      const certPath = `${envelopeId}/certificate.pdf`;

      await pool.query(
        `insert into envelopes (
          envelope_id, status, pdf_hash, pdf_path, certificate_path,
          pdf_bytes, certificate_bytes,
          created_at, viewed_at, signed_at,
          ip_address, user_agent, signed_ip, signed_user_agent,
          occu_med_rep_name, occu_med_rep_title,
          clinic_rep_name, clinic_rep_title,
          agreed_electronic, recipient_email, payload, updated_at
        ) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,now())
        on conflict (envelope_id) do update set
          status = excluded.status,
          pdf_hash = excluded.pdf_hash,
          pdf_path = excluded.pdf_path,
          certificate_path = excluded.certificate_path,
          pdf_bytes = excluded.pdf_bytes,
          certificate_bytes = excluded.certificate_bytes,
          created_at = excluded.created_at,
          viewed_at = excluded.viewed_at,
          signed_at = excluded.signed_at,
          ip_address = excluded.ip_address,
          user_agent = excluded.user_agent,
          signed_ip = excluded.signed_ip,
          signed_user_agent = excluded.signed_user_agent,
          occu_med_rep_name = excluded.occu_med_rep_name,
          occu_med_rep_title = excluded.occu_med_rep_title,
          clinic_rep_name = excluded.clinic_rep_name,
          clinic_rep_title = excluded.clinic_rep_title,
          agreed_electronic = excluded.agreed_electronic,
          recipient_email = excluded.recipient_email,
          payload = excluded.payload,
          updated_at = now()`,
        [
          envelopeId, "signed", pdfHash, pdfPath, certPath,
          Buffer.from(pdfBytes), Buffer.from(certBytes),
          createdAt, effectiveViewedAt, signedAt,
          ip, userAgent, ip, userAgent,
          data.occuMedRepName, data.occuMedRepTitle,
          data.clinicRepFullName, data.clinicRepTitle,
          Boolean(data.agreedElectronic), recipientEmail || null,
          JSON.stringify(data),
        ]
      );

      await maybeSendEmail({ to: recipientEmail, envelopeId, pdfHash, pdfBytes, certBytes });

      return sendJson(res, 200, {
        envelopeId,
        signedAt,
        createdAt,
        viewedAt: effectiveViewedAt,
        ipAddress: ip,
        userAgent,
        pdfHash,
        pdfBase64: Buffer.from(pdfBytes).toString("base64"),
        certificateBase64: Buffer.from(certBytes).toString("base64"),
      });
    }

    if (req.method === "POST" && url.pathname === "/api/memos/send") {
      const body = await readJson(req);
      const { recipientEmail, subject, message, pdfBase64, filename } = body || {};
      if (!recipientEmail || !pdfBase64) return sendJson(res, 400, { error: "recipientEmail and pdfBase64 are required." });
      if (typeof pdfBase64 !== "string" || pdfBase64.length > 25_000_000) {
        return sendJson(res, 413, { error: "PDF payload too large. Please reduce file size and try again." });
      }
      const pdfBytes = base64ToUint8(pdfBase64);
      await sendMemoEmail({
        to: recipientEmail,
        subject: subject || "Occu-Med Memo",
        text: message || "Please find the attached memo.",
        pdfBytes,
        filename: filename || "memo.pdf",
      });
      return sendJson(res, 200, { ok: true });
    }

    return sendJson(res, 404, { error: "Not found" });
  } catch (error) {
    return sendJson(res, 500, { error: String(error) });
  }
});

const port = Number(process.env.PORT || 3001);

async function start() {
  try {
    await initDbPool();
    await initDb();
  } catch (error) {
    console.error("database initialization failed:", error.message);
  }
  server.listen(port, () => {
    console.log(`occu-med backend listening on :${port}`);
  });
}

start();
