import crypto from "node:crypto";
import http from "node:http";
import { URL } from "node:url";
import pg from "pg";
import { generateCertificatePdf, generateSignedPdf } from "./pdf.mjs";

const { Pool } = pg;

const ENVELOPE_PREFIX = process.env.ENVELOPE_PREFIX || "OM";
const FRONTEND_ORIGIN = process.env.FRONTEND_ORIGIN || "*";
const FRONTEND_APP_URL = (process.env.FRONTEND_APP_URL || (FRONTEND_ORIGIN !== "*" ? FRONTEND_ORIGIN : "")).replace(/\/$/, "");
const INVITATION_TTL_DAYS = Math.min(365, Math.max(1, Number(process.env.INVITATION_TTL_DAYS || 30) || 30));
const PROVIDER_RESPONSES_TO = process.env.PROVIDER_RESPONSES_TO || "";
const ADMIN_ACCESS_KEY = process.env.ADMIN_ACCESS_KEY || "";

let pool = null;
const rateWindows = new Map();

function sanitizeDatabaseUrl(raw) {
  if (!raw) return "";
  let url = raw.trim();
  if (!url) return "";
  url = url.replace(/[?&]channel_binding=[^&]*/gi, "");
  url = url.replace(/\?$/, "").replace(/&$/, "");
  if (process.env.NODE_ENV === "production" && !/sslmode=/i.test(url)) {
    const sep = url.includes("?") ? "&" : "?";
    url = `${url}${sep}sslmode=require`;
  }
  return url;
}

async function initDbPool() {
  const connStr = sanitizeDatabaseUrl(process.env.DATABASE_URL || "");
  if (!connStr) {
    console.warn("DATABASE_URL not set; database operations will fail at runtime");
    return;
  }
  pool = new Pool({
    connectionString: connStr,
    ssl: process.env.NODE_ENV === "production" ? { rejectUnauthorized: false } : false,
  });
  try {
    const client = await pool.connect();
    try {
      await client.query("select 1");
    } finally {
      client.release();
    }
    console.log("neon database connection ok");
  } catch (err) {
    console.error("neon database connection failed:", err.message);
    await pool.end().catch(() => undefined);
    pool = null;
    throw err;
  }
}

async function initDb() {
  if (!pool) return;
  await pool.query("create extension if not exists pgcrypto");
  await pool.query(`
    create table if not exists envelopes (
      id bigint generated by default as identity primary key,
      envelope_id text unique not null,
      status text,
      created_at timestamptz,
      viewed_at timestamptz,
      signed_at timestamptz,
      ip_address text,
      user_agent text,
      viewed_ip text,
      viewed_user_agent text,
      signed_ip text,
      signed_user_agent text,
      pdf_hash text,
      pdf_path text,
      certificate_path text,
      pdf_bytes bytea,
      certificate_bytes bytea,
      occu_med_rep_name text,
      occu_med_rep_title text,
      clinic_rep_name text,
      clinic_rep_title text,
      agreed_electronic boolean,
      recipient_email text,
      payload jsonb,
      updated_at timestamptz not null default now()
    );
  `);
  await pool.query(`
    create table if not exists provider_invitations (
      id bigint generated by default as identity primary key,
      token_hash text unique not null,
      document_type text not null,
      status text not null default 'sent',
      recipient_email text,
      payload jsonb not null,
      completed_payload jsonb,
      created_at timestamptz not null default now(),
      expires_at timestamptz not null,
      viewed_at timestamptz,
      completed_at timestamptz,
      created_ip text,
      created_user_agent text,
      viewed_ip text,
      viewed_user_agent text,
      completed_ip text,
      completed_user_agent text,
      pdf_hash text,
      pdf_bytes bytea,
      certificate_bytes bytea,
      updated_at timestamptz not null default now()
    );
    create index if not exists provider_invitations_status_idx
      on provider_invitations (status, expires_at);
  `);
  await pool.query("alter table provider_invitations add column if not exists certificate_bytes bytea");
  console.log("database initialized");
}

function newEnvelopeId() {
  const rand = crypto.randomBytes(8).toString("hex").toUpperCase();
  return `${ENVELOPE_PREFIX}-${Date.now().toString(36).toUpperCase()}-${rand}`;
}

function newInvitationToken() {
  return crypto.randomBytes(32).toString("base64url");
}

function tokenHash(token) {
  return crypto.createHash("sha256").update(token).digest("hex");
}

function requireDatabase() {
  if (!pool) throw new Error("Database is not configured");
}

function sha256Hex(bytes) {
  return crypto.createHash("sha256").update(bytes).digest("hex");
}

function base64ToUint8(base64) {
  return Uint8Array.from(Buffer.from(base64, "base64"));
}

function limitedText(value, maxLength = 300) {
  return typeof value === "string" ? value.trim().slice(0, maxLength) : "";
}

function buildCompletedProviderData(original, submitted, completedAt) {
  const originalServices = new Map((original.services || []).map((service) => [service.id, service]));
  const services = (submitted.services || []).slice(0, 250).map((service, index) => {
    const originalService = originalServices.get(service?.id);
    return {
      id: originalService?.id || `provider-service-${index + 1}`,
      component: limitedText(service?.component, 300),
      price: limitedText(service?.price, 100),
      source: originalService ? "occu-med" : "provider",
    };
  }).filter((service) => service.component);

  return {
    ...original,
    providerName: limitedText(submitted.providerName) || original.providerName,
    providerContactName: limitedText(submitted.providerContactName),
    providerEmail: limitedText(submitted.providerEmail),
    providerPhone: limitedText(submitted.providerPhone),
    address: {
      street1: limitedText(submitted.address?.street1),
      street2: limitedText(submitted.address?.street2),
      city: limitedText(submitted.address?.city),
      state: limitedText(submitted.address?.state),
      zip: limitedText(submitted.address?.zip, 40),
    },
    services,
    providerSignerName: limitedText(submitted.providerSignerName),
    providerSignerTitle: limitedText(submitted.providerSignerTitle),
    providerSignedDate: completedAt.slice(0, 10),
    agreedElectronic: true,
  };
}

function getClientIp(req) {
  const fwd = req.headers["x-forwarded-for"];
  if (typeof fwd === "string" && fwd.length > 0) return fwd.split(",")[0].trim();
  return req.socket.remoteAddress || "unknown";
}

function allowRequest(req, bucket, limit, windowMs = 60 * 60 * 1000) {
  const now = Date.now();
  if (rateWindows.size > 10_000) {
    for (const [storedKey, value] of rateWindows) {
      if (value.resetAt <= now) rateWindows.delete(storedKey);
    }
  }
  const key = `${bucket}:${getClientIp(req)}`;
  const current = rateWindows.get(key);
  if (!current || current.resetAt <= now) {
    rateWindows.set(key, { count: 1, resetAt: now + windowMs });
    return true;
  }
  if (current.count >= limit) return false;
  current.count += 1;
  return true;
}

function sendJson(res, status, body) {
  res.writeHead(status, {
    "Content-Type": "application/json",
    "Access-Control-Allow-Origin": FRONTEND_ORIGIN,
    "Access-Control-Allow-Headers": "Content-Type, X-Admin-Key",
    "Access-Control-Allow-Methods": "GET,POST,OPTIONS",
  });
  res.end(JSON.stringify(body));
}

function sendPdf(res, bytes, filename) {
  res.writeHead(200, {
    "Content-Type": "application/pdf",
    "Content-Disposition": `attachment; filename="${filename.replace(/[^a-z0-9_.-]/gi, "-")}"`,
    "Content-Length": bytes.length,
    "Access-Control-Allow-Origin": FRONTEND_ORIGIN,
    "Access-Control-Allow-Headers": "Content-Type, X-Admin-Key",
  });
  res.end(bytes);
}

function hasAdminAccess(req) {
  const supplied = typeof req.headers["x-admin-key"] === "string" ? req.headers["x-admin-key"] : "";
  if (!ADMIN_ACCESS_KEY || !supplied) return false;
  const expectedBytes = Buffer.from(ADMIN_ACCESS_KEY);
  const suppliedBytes = Buffer.from(supplied);
  return expectedBytes.length === suppliedBytes.length && crypto.timingSafeEqual(expectedBytes, suppliedBytes);
}

function requireAdminAccess(req, res) {
  if (!ADMIN_ACCESS_KEY) {
    sendJson(res, 503, { error: "Admin access is not configured on the backend." });
    return false;
  }
  if (!hasAdminAccess(req)) {
    sendJson(res, 401, { error: "The admin access code is incorrect." });
    return false;
  }
  return true;
}

function adminInvitationRow(row, includeData = false) {
  const data = row.completed_payload || row.payload || {};
  const result = {
    id: String(row.id),
    documentType: row.document_type,
    status: row.status,
    providerName: data.providerName || "Unnamed provider",
    documentNumber: data.documentNumber || `Invitation ${row.id}`,
    recipientEmail: row.recipient_email || data.providerEmail || "",
    createdAt: row.created_at,
    expiresAt: row.expires_at,
    viewedAt: row.viewed_at || undefined,
    completedAt: row.completed_at || undefined,
    hasCompletedDocument: Boolean(row.pdf_bytes),
  };
  if (includeData) {
    result.data = data;
    result.pdfHash = row.pdf_hash || undefined;
  }
  return result;
}

function readJson(req) {
  return new Promise((resolve, reject) => {
    let raw = "";
    req.on("data", (chunk) => {
      raw += chunk;
      if (raw.length > 12_000_000) {
        reject(new Error("Payload too large"));
        req.destroy();
      }
    });
    req.on("end", () => {
      try {
        resolve(raw ? JSON.parse(raw) : {});
      } catch (e) {
        reject(e);
      }
    });
    req.on("error", reject);
  });
}


async function maybeSendEmail({ to, envelopeId, pdfHash, pdfBytes, certBytes }) {
  const apiKey = process.env.RESEND_API_KEY;
  const from = process.env.MAIL_FROM;
  if (!to || !apiKey || !from) return;

  await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from,
      to,
      subject: `Signed Clinic Memo ${envelopeId}`,
      text: `Envelope ${envelopeId} has been finalized.\nSHA-256: ${pdfHash}`,
      attachments: [
        { filename: `${envelopeId}-signed.pdf`, content: Buffer.from(pdfBytes).toString("base64") },
        { filename: `${envelopeId}-certificate.pdf`, content: Buffer.from(certBytes).toString("base64") },
      ],
    }),
  });
}

async function sendMemoEmail({ to, subject, text, pdfBytes, filename }) {
  const apiKey = process.env.RESEND_API_KEY;
  const from = process.env.MAIL_FROM;
  if (!to || !apiKey || !from) {
    throw new Error("Email provider not configured");
  }

  const response = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from,
      to,
      subject,
      text,
      attachments: [
        { filename, content: Buffer.from(pdfBytes).toString("base64") },
      ],
    }),
  });

  if (!response.ok) {
    const details = await response.text();
    throw new Error(`Resend send failed (${response.status}): ${details}`);
  }
}

async function maybeSendProviderInvitation({ to, providerUrl, documentType, providerName }) {
  const apiKey = process.env.RESEND_API_KEY;
  const from = process.env.MAIL_FROM;
  if (!to || !apiKey || !from || !providerUrl) return false;

  const label = documentType === "fee-proposal" ? "Provider Fee Proposal" : "Provider Service Agreement";
  const response = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from,
      to,
      subject: `Occu-Med ${label}${providerName ? ` - ${providerName}` : ""}`,
      text: `Occu-Med has invited you to review and complete a ${label}.\n\nOpen your secure document: ${providerUrl}\n\nThis link is specific to your document and expires in ${INVITATION_TTL_DAYS} days.`,
    }),
  });
  if (!response.ok) {
    const details = await response.text();
    throw new Error(`Invitation email failed (${response.status}): ${details}`);
  }
  return true;
}

async function maybeSendCompletedProviderDocument({ data, recipientEmail, pdfBytes, certificateBytes }) {
  const apiKey = process.env.RESEND_API_KEY;
  const from = process.env.MAIL_FROM;
  if (!apiKey || !from) return false;
  const recipients = [...new Set([PROVIDER_RESPONSES_TO, recipientEmail || data.providerEmail].filter(Boolean))];
  if (!recipients.length) return false;

  const label = data.documentType === "fee-proposal" ? "Provider Fee Proposal" : "Provider Service Agreement";
  const response = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      from,
      to: recipients,
      subject: `Completed Occu-Med ${label} - ${data.providerName}`,
      text: `${data.providerName} completed document ${data.documentNumber}. The completed document and audit certificate are attached.`,
      attachments: [
        { filename: `${data.documentNumber}-completed.pdf`, content: Buffer.from(pdfBytes).toString("base64") },
        { filename: `${data.documentNumber}-certificate.pdf`, content: Buffer.from(certificateBytes).toString("base64") },
      ],
    }),
  });
  if (!response.ok) throw new Error(`Completed-document email failed (${response.status}): ${await response.text()}`);
  return true;
}

async function getEnvelope(envelopeId) {
  const { rows } = await pool.query(
    "select envelope_id, created_at, viewed_at from envelopes where envelope_id = $1",
    [envelopeId]
  );
  return rows.length > 0 ? rows[0] : null;
}

const server = http.createServer(async (req, res) => {
  if (req.method === "OPTIONS") {
    res.writeHead(204, {
      "Access-Control-Allow-Origin": FRONTEND_ORIGIN,
      "Access-Control-Allow-Headers": "Content-Type, X-Admin-Key",
      "Access-Control-Allow-Methods": "GET,POST,OPTIONS",
    });
    return res.end();
  }

  const url = new URL(req.url || "/", `http://${req.headers.host}`);

  try {
    if (req.method === "GET" && url.pathname === "/health") {
      return sendJson(res, 200, { ok: true, databaseConfigured: Boolean(pool), service: "occu-med-backend", timestamp: new Date().toISOString() });
    }

    if (req.method === "GET" && url.pathname === "/api/admin/session") {
      if (!allowRequest(req, "admin-session", 120)) return sendJson(res, 429, { error: "Too many sign-in attempts. Please try again later." });
      if (!requireAdminAccess(req, res)) return;
      return sendJson(res, 200, { ok: true });
    }

    if (req.method === "GET" && url.pathname === "/api/admin/provider-invitations") {
      if (!requireAdminAccess(req, res)) return;
      requireDatabase();
      await pool.query(
        "update provider_invitations set status = 'expired', updated_at = now() where status in ('sent','viewed') and expires_at < now()",
      );
      const allowedStatuses = new Set(["sent", "viewed", "completed", "expired", "cancelled"]);
      const status = allowedStatuses.has(url.searchParams.get("status")) ? url.searchParams.get("status") : "";
      const query = limitedText(url.searchParams.get("q"), 120);
      const likeQuery = `%${query}%`;
      const { rows } = await pool.query(
        `select id, document_type, status, recipient_email, payload, completed_payload,
                created_at, expires_at, viewed_at, completed_at, pdf_bytes
           from provider_invitations
          where ($1 = '' or status = $1)
            and ($2 = '' or recipient_email ilike $3
              or coalesce(completed_payload, payload)->>'providerName' ilike $3
              or coalesce(completed_payload, payload)->>'documentNumber' ilike $3)
          order by created_at desc
          limit 200`,
        [status, query, likeQuery],
      );
      const countResult = await pool.query(
        `select status, count(*)::int as count from provider_invitations group by status`,
      );
      const counts = { all: 0, sent: 0, viewed: 0, completed: 0, expired: 0, cancelled: 0 };
      for (const row of countResult.rows) {
        if (Object.hasOwn(counts, row.status)) counts[row.status] = Number(row.count);
        counts.all += Number(row.count);
      }
      return sendJson(res, 200, { items: rows.map((row) => adminInvitationRow(row)), counts });
    }

    const adminInvitationMatch = url.pathname.match(/^\/api\/admin\/provider-invitations\/(\d+)$/);
    if (req.method === "GET" && adminInvitationMatch) {
      if (!requireAdminAccess(req, res)) return;
      requireDatabase();
      const { rows } = await pool.query(
        `select id, document_type, status, recipient_email, payload, completed_payload,
                created_at, expires_at, viewed_at, completed_at, pdf_hash, pdf_bytes
           from provider_invitations where id = $1`,
        [adminInvitationMatch[1]],
      );
      if (!rows.length) return sendJson(res, 404, { error: "Invitation not found." });
      return sendJson(res, 200, adminInvitationRow(rows[0], true));
    }

    const adminResendMatch = url.pathname.match(/^\/api\/admin\/provider-invitations\/(\d+)\/resend$/);
    if (req.method === "POST" && adminResendMatch) {
      if (!requireAdminAccess(req, res)) return;
      requireDatabase();
      const { rows } = await pool.query(
        "select status, document_type, recipient_email, payload from provider_invitations where id = $1",
        [adminResendMatch[1]],
      );
      if (!rows.length) return sendJson(res, 404, { error: "Invitation not found." });
      if (rows[0].status === "completed") return sendJson(res, 409, { error: "A completed invitation cannot be resent." });
      if (rows[0].status === "cancelled") return sendJson(res, 409, { error: "A cancelled invitation cannot be resent." });
      const token = newInvitationToken();
      const expiresAt = new Date(Date.now() + INVITATION_TTL_DAYS * 24 * 60 * 60 * 1000);
      await pool.query(
        `update provider_invitations set token_hash = $2, status = 'sent', expires_at = $3,
          viewed_at = null, viewed_ip = null, viewed_user_agent = null, updated_at = now() where id = $1`,
        [adminResendMatch[1], tokenHash(token), expiresAt.toISOString()],
      );
      const providerPath = `/provider/${token}`;
      const providerUrl = FRONTEND_APP_URL ? `${FRONTEND_APP_URL}${providerPath}` : "";
      let emailSent = false;
      try {
        emailSent = await maybeSendProviderInvitation({
          to: rows[0].recipient_email,
          providerUrl,
          documentType: rows[0].document_type,
          providerName: rows[0].payload?.providerName,
        });
      } catch (error) {
        console.error("provider invitation resend failed", error);
      }
      return sendJson(res, 200, { providerPath, expiresAt: expiresAt.toISOString(), emailSent });
    }

    const adminCancelMatch = url.pathname.match(/^\/api\/admin\/provider-invitations\/(\d+)\/cancel$/);
    if (req.method === "POST" && adminCancelMatch) {
      if (!requireAdminAccess(req, res)) return;
      requireDatabase();
      const result = await pool.query(
        "update provider_invitations set status = 'cancelled', updated_at = now() where id = $1 and status not in ('completed','cancelled') returning id",
        [adminCancelMatch[1]],
      );
      if (!result.rowCount) return sendJson(res, 409, { error: "Only an active invitation can be cancelled." });
      return sendJson(res, 200, { ok: true, status: "cancelled" });
    }

    const adminFileMatch = url.pathname.match(/^\/api\/admin\/provider-invitations\/(\d+)\/(document|certificate)$/);
    if (req.method === "GET" && adminFileMatch) {
      if (!requireAdminAccess(req, res)) return;
      requireDatabase();
      const column = adminFileMatch[2] === "document" ? "pdf_bytes" : "certificate_bytes";
      const { rows } = await pool.query(
        `select ${column} as bytes, coalesce(completed_payload, payload)->>'documentNumber' as document_number
           from provider_invitations where id = $1`,
        [adminFileMatch[1]],
      );
      if (!rows.length || !rows[0].bytes) return sendJson(res, 404, { error: "The completed file is not available." });
      return sendPdf(res, rows[0].bytes, `${rows[0].document_number || "provider-document"}-${adminFileMatch[2]}.pdf`);
    }

    if (req.method === "POST" && url.pathname === "/api/provider-invitations") {
      if (!allowRequest(req, "provider-invitation-create", 30)) {
        return sendJson(res, 429, { error: "Too many invitations created. Please try again later." });
      }
      if (!requireAdminAccess(req, res)) return;
      requireDatabase();
      const body = await readJson(req);
      const { documentType, data, recipientEmail } = body || {};
      if (!["fee-proposal", "service-agreement"].includes(documentType)) {
        return sendJson(res, 400, { error: "Unsupported document type." });
      }
      if (!data?.providerName || !Array.isArray(data?.services) || data.services.length === 0 || data.services.length > 250) {
        return sendJson(res, 400, { error: "Provider name and at least one service are required." });
      }

      const token = newInvitationToken();
      const hash = tokenHash(token);
      const createdAt = new Date();
      const expiresAt = new Date(createdAt.getTime() + INVITATION_TTL_DAYS * 24 * 60 * 60 * 1000);
      await pool.query(
        `insert into provider_invitations (
          token_hash, document_type, status, recipient_email, payload,
          created_at, expires_at, created_ip, created_user_agent
        ) values ($1,$2,'sent',$3,$4,$5,$6,$7,$8)`,
        [
          hash,
          documentType,
          recipientEmail || null,
          JSON.stringify(data),
          createdAt.toISOString(),
          expiresAt.toISOString(),
          getClientIp(req),
          req.headers["user-agent"] || "unknown",
        ],
      );

      const providerPath = `/provider/${token}`;
      const providerUrl = FRONTEND_APP_URL ? `${FRONTEND_APP_URL}${providerPath}` : "";
      let emailSent = false;
      let emailError;
      try {
        emailSent = await maybeSendProviderInvitation({
          to: recipientEmail,
          providerUrl,
          documentType,
          providerName: data.providerName,
        });
      } catch (error) {
        emailError = String(error);
        console.error("provider invitation email failed", error);
      }
      return sendJson(res, 201, {
        token,
        providerPath,
        createdAt: createdAt.toISOString(),
        expiresAt: expiresAt.toISOString(),
        emailSent,
        emailError,
      });
    }

    const invitationMatch = url.pathname.match(/^\/api\/provider-invitations\/([^/]+)$/);
    if (req.method === "GET" && invitationMatch) {
      if (!allowRequest(req, "provider-invitation-view", 300)) {
        return sendJson(res, 429, { error: "Too many invitation requests. Please try again later." });
      }
      requireDatabase();
      const token = decodeURIComponent(invitationMatch[1]);
      const hash = tokenHash(token);
      const { rows } = await pool.query(
        `select document_type, status, payload, completed_payload, created_at, expires_at, completed_at
         from provider_invitations where token_hash = $1`,
        [hash],
      );
      if (!rows.length) return sendJson(res, 404, { error: "Invitation not found." });
      const invite = rows[0];
      if (invite.status === "cancelled") return sendJson(res, 410, { error: "Invitation cancelled." });
      const expired = new Date(invite.expires_at).getTime() < Date.now() && invite.status !== "completed";
      if (expired) {
        await pool.query("update provider_invitations set status = 'expired', updated_at = now() where token_hash = $1", [hash]);
        return sendJson(res, 410, { error: "Invitation expired." });
      }
      if (invite.status !== "completed") {
        await pool.query(
          `update provider_invitations set
             status = 'viewed', viewed_at = coalesce(viewed_at, now()),
             viewed_ip = $2, viewed_user_agent = $3, updated_at = now()
           where token_hash = $1`,
          [hash, getClientIp(req), req.headers["user-agent"] || "unknown"],
        );
      }
      return sendJson(res, 200, {
        documentType: invite.document_type,
        status: invite.status === "completed" ? "completed" : "viewed",
        data: invite.completed_payload || invite.payload,
        createdAt: invite.created_at,
        expiresAt: invite.expires_at,
        completedAt: invite.completed_at || undefined,
      });
    }

    const invitationFinalizeMatch = url.pathname.match(/^\/api\/provider-invitations\/([^/]+)\/finalize$/);
    if (req.method === "POST" && invitationFinalizeMatch) {
      if (!allowRequest(req, "provider-invitation-finalize", 60)) {
        return sendJson(res, 429, { error: "Too many completion attempts. Please try again later." });
      }
      requireDatabase();
      const token = decodeURIComponent(invitationFinalizeMatch[1]);
      const hash = tokenHash(token);
      const body = await readJson(req);
      const { data, signedPdfBase64 } = body || {};
      if (!data?.providerSignerName || !data?.providerSignerTitle || !data?.agreedElectronic) {
        return sendJson(res, 400, { error: "Provider name, title, and electronic signature consent are required." });
      }
      if (!Array.isArray(data?.services) || !data.services.some((service) => service?.component)) {
        return sendJson(res, 400, { error: "At least one service is required." });
      }
      if (typeof signedPdfBase64 !== "string" || !signedPdfBase64 || signedPdfBase64.length > 25_000_000) {
        return sendJson(res, 413, { error: "The completed PDF is missing or too large." });
      }
      const { rows } = await pool.query(
        "select status, expires_at, created_at, viewed_at, payload, recipient_email from provider_invitations where token_hash = $1",
        [hash],
      );
      if (!rows.length) return sendJson(res, 404, { error: "Invitation not found." });
      if (rows[0].status === "completed") return sendJson(res, 409, { error: "Invitation has already been completed." });
      if (new Date(rows[0].expires_at).getTime() < Date.now()) return sendJson(res, 410, { error: "Invitation expired." });

      const pdfBytes = base64ToUint8(signedPdfBase64);
      if (Buffer.from(pdfBytes.subarray(0, 5)).toString("ascii") !== "%PDF-") {
        return sendJson(res, 400, { error: "The completed document is not a valid PDF." });
      }
      const pdfHash = sha256Hex(pdfBytes);
      const completedAt = new Date().toISOString();
      const completedData = buildCompletedProviderData(rows[0].payload, data, completedAt);
      if (!completedData.services.length) return sendJson(res, 400, { error: "At least one service is required." });
      if (!completedData.providerSignerName || !completedData.providerSignerTitle) {
        return sendJson(res, 400, { error: "Provider name and title are required." });
      }
      const certificateBytes = await generateCertificatePdf({
        envelopeId: completedData.documentNumber,
        pdfHash,
        audit: {
          createdAt: new Date(rows[0].created_at).toISOString(),
          viewedAt: rows[0].viewed_at ? new Date(rows[0].viewed_at).toISOString() : completedAt,
          signedAt: completedAt,
          ipAddress: getClientIp(req),
          userAgent: req.headers["user-agent"] || "unknown",
          occuMedRepName: completedData.preparedBy || "Occu-Med",
          clinicRepFullName: completedData.providerSignerName,
          agreedElectronic: true,
        },
      });
      const completionResult = await pool.query(
        `update provider_invitations set
           status = 'completed', completed_payload = $2, completed_at = $3,
           completed_ip = $4, completed_user_agent = $5,
           pdf_hash = $6, pdf_bytes = $7, certificate_bytes = $8, updated_at = now()
         where token_hash = $1 and status <> 'completed'
         returning id`,
        [
          hash,
          JSON.stringify(completedData),
          completedAt,
          getClientIp(req),
          req.headers["user-agent"] || "unknown",
          pdfHash,
          Buffer.from(pdfBytes),
          Buffer.from(certificateBytes),
        ],
      );
      if (!completionResult.rowCount) return sendJson(res, 409, { error: "Invitation has already been completed." });
      let emailSent = false;
      try {
        emailSent = await maybeSendCompletedProviderDocument({
          data: completedData,
          recipientEmail: rows[0].recipient_email,
          pdfBytes,
          certificateBytes,
        });
      } catch (error) {
        console.error("completed provider document email failed", error);
      }
      return sendJson(res, 200, {
        ok: true,
        completedAt,
        pdfHash,
        pdfBase64: Buffer.from(pdfBytes).toString("base64"),
        certificateBase64: Buffer.from(certificateBytes).toString("base64"),
        emailSent,
      });
    }

    if (req.method === "POST" && url.pathname === "/api/signed/envelopes") {
      if (!allowRequest(req, "signed-envelope-create", 60)) {
        return sendJson(res, 429, { error: "Too many envelope requests. Please try again later." });
      }
      requireDatabase();
      const envelopeId = newEnvelopeId();
      const createdAt = new Date().toISOString();
      const ip = getClientIp(req);
      const userAgent = req.headers["user-agent"] || "unknown";

      await pool.query(
        "insert into envelopes (envelope_id, created_at, ip_address, user_agent, status) values ($1, $2, $3, $4, $5)",
        [envelopeId, createdAt, ip, userAgent, "created"]
      );

      return sendJson(res, 200, { envelopeId, createdAt });
    }

    const viewMatch = url.pathname.match(/^\/api\/signed\/envelopes\/([^/]+)\/view$/);
    if (req.method === "POST" && viewMatch) {
      const envelopeId = decodeURIComponent(viewMatch[1]);
      const viewedAt = new Date().toISOString();
      const ip = getClientIp(req);
      const ua = req.headers["user-agent"] || "unknown";

      await pool.query(
        `insert into envelopes (envelope_id, viewed_at, viewed_ip, viewed_user_agent, status, created_at, updated_at)
         values ($1, $2, $3, $4, $5, $2, now())
         on conflict (envelope_id) do update set
           viewed_at = excluded.viewed_at,
           viewed_ip = excluded.viewed_ip,
           viewed_user_agent = excluded.viewed_user_agent,
           status = excluded.status,
           updated_at = now()`,
        [envelopeId, viewedAt, ip, ua, "viewed"]
      );

      return sendJson(res, 200, { envelopeId, viewedAt });
    }

    const finalizeMatch = url.pathname.match(/^\/api\/signed\/envelopes\/([^/]+)\/finalize$/);
    if (req.method === "POST" && finalizeMatch) {
      const envelopeId = decodeURIComponent(finalizeMatch[1]);
      const body = await readJson(req);
      const { data, viewedAt, recipientEmail, signedPdfBase64 } = body;

      if (!data?.agreedElectronic) return sendJson(res, 400, { error: "Agreement required." });
      if (!data?.occuMedRepName || !data?.clinicRepFullName) {
        return sendJson(res, 400, { error: "Both signatures are required." });
      }

      const signedAt = new Date().toISOString();
      const existingEnvelope = await getEnvelope(envelopeId);
      const createdAt = existingEnvelope?.created_at || signedAt;
      const effectiveViewedAt = viewedAt || existingEnvelope?.viewed_at || signedAt;
      const ip = getClientIp(req);
      const userAgent = req.headers["user-agent"] || "unknown";

      const pdfBytes = signedPdfBase64
        ? base64ToUint8(signedPdfBase64)
        : await generateSignedPdf({ envelopeId, data, signedAt, viewedAt: effectiveViewedAt, ip, userAgent });

      const pdfHash = sha256Hex(pdfBytes);
      const certBytes = await generateCertificatePdf({
        envelopeId,
        pdfHash,
        audit: {
          createdAt,
          viewedAt: effectiveViewedAt,
          signedAt,
          ipAddress: ip,
          userAgent,
          occuMedRepName: data.occuMedRepName,
          clinicRepFullName: data.clinicRepFullName,
          agreedElectronic: Boolean(data.agreedElectronic),
        },
      });

      const pdfPath = `${envelopeId}/document.pdf`;
      const certPath = `${envelopeId}/certificate.pdf`;

      await pool.query(
        `insert into envelopes (
          envelope_id, status, pdf_hash, pdf_path, certificate_path,
          pdf_bytes, certificate_bytes,
          created_at, viewed_at, signed_at,
          ip_address, user_agent, signed_ip, signed_user_agent,
          occu_med_rep_name, occu_med_rep_title,
          clinic_rep_name, clinic_rep_title,
          agreed_electronic, recipient_email, payload, updated_at
        ) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,now())
        on conflict (envelope_id) do update set
          status = excluded.status,
          pdf_hash = excluded.pdf_hash,
          pdf_path = excluded.pdf_path,
          certificate_path = excluded.certificate_path,
          pdf_bytes = excluded.pdf_bytes,
          certificate_bytes = excluded.certificate_bytes,
          created_at = excluded.created_at,
          viewed_at = excluded.viewed_at,
          signed_at = excluded.signed_at,
          ip_address = excluded.ip_address,
          user_agent = excluded.user_agent,
          signed_ip = excluded.signed_ip,
          signed_user_agent = excluded.signed_user_agent,
          occu_med_rep_name = excluded.occu_med_rep_name,
          occu_med_rep_title = excluded.occu_med_rep_title,
          clinic_rep_name = excluded.clinic_rep_name,
          clinic_rep_title = excluded.clinic_rep_title,
          agreed_electronic = excluded.agreed_electronic,
          recipient_email = excluded.recipient_email,
          payload = excluded.payload,
          updated_at = now()`,
        [
          envelopeId, "signed", pdfHash, pdfPath, certPath,
          Buffer.from(pdfBytes), Buffer.from(certBytes),
          createdAt, effectiveViewedAt, signedAt,
          ip, userAgent, ip, userAgent,
          data.occuMedRepName, data.occuMedRepTitle,
          data.clinicRepFullName, data.clinicRepTitle,
          Boolean(data.agreedElectronic), recipientEmail || null,
          JSON.stringify(data),
        ]
      );

      await maybeSendEmail({ to: recipientEmail, envelopeId, pdfHash, pdfBytes, certBytes });

      return sendJson(res, 200, {
        envelopeId,
        signedAt,
        createdAt,
        viewedAt: effectiveViewedAt,
        ipAddress: ip,
        userAgent,
        pdfHash,
        pdfBase64: Buffer.from(pdfBytes).toString("base64"),
        certificateBase64: Buffer.from(certBytes).toString("base64"),
      });
    }

    if (req.method === "POST" && url.pathname === "/api/memos/send") {
      if (!allowRequest(req, "memo-send", 60)) {
        return sendJson(res, 429, { error: "Too many email requests. Please try again later." });
      }
      const body = await readJson(req);
      const { recipientEmail, subject, message, pdfBase64, filename } = body || {};
      if (!recipientEmail || !pdfBase64) return sendJson(res, 400, { error: "recipientEmail and pdfBase64 are required." });
      if (typeof pdfBase64 !== "string" || pdfBase64.length > 25_000_000) {
        return sendJson(res, 413, { error: "PDF payload too large. Please reduce file size and try again." });
      }
      const pdfBytes = base64ToUint8(pdfBase64);
      await sendMemoEmail({
        to: recipientEmail,
        subject: subject || "Occu-Med Memo",
        text: message || "Please find the attached memo.",
        pdfBytes,
        filename: filename || "memo.pdf",
      });
      return sendJson(res, 200, { ok: true });
    }

    return sendJson(res, 404, { error: "Not found" });
  } catch (error) {
    return sendJson(res, 500, { error: String(error) });
  }
});

const port = Number(process.env.PORT || 3001);

async function start() {
  try {
    await initDbPool();
    await initDb();
  } catch (error) {
    console.error("database initialization failed:", error.message);
  }
  server.listen(port, () => {
    console.log(`occu-med backend listening on :${port}`);
  });
}

start();
