import crypto from "node:crypto";
import http from "node:http";
import { URL } from "node:url";
import pg from "pg";
import { sanitizeDatabaseUrl } from "./database-url.mjs";
import {
  ADMIN_ROLES,
  hasPermission,
  hashPassword,
  normalizeEmail,
  passwordValidationError,
  publicAdminUser,
  verifyPassword,
} from "./auth.mjs";
import { generateCertificatePdf, generateSignedPdf } from "./pdf.mjs";

const { Pool } = pg;

const ENVELOPE_PREFIX = process.env.ENVELOPE_PREFIX || "OM";
const FRONTEND_ORIGIN = process.env.FRONTEND_ORIGIN || "*";
const FRONTEND_APP_URL = (process.env.FRONTEND_APP_URL || (FRONTEND_ORIGIN !== "*" ? FRONTEND_ORIGIN : "")).replace(/\/$/, "");
const INVITATION_TTL_DAYS = Math.min(365, Math.max(1, Number(process.env.INVITATION_TTL_DAYS || 30) || 30));
const PROVIDER_RESPONSES_TO = process.env.PROVIDER_RESPONSES_TO || "";
const ADMIN_SESSION_HOURS = Math.min(24, Math.max(1, Number(process.env.ADMIN_SESSION_HOURS || 8) || 8));
const ADMIN_IDLE_MINUTES = Math.min(240, Math.max(5, Number(process.env.ADMIN_IDLE_MINUTES || 30) || 30));
const INITIAL_ADMIN_EMAIL = normalizeEmail(process.env.INITIAL_ADMIN_EMAIL || "");
const INITIAL_ADMIN_PASSWORD = process.env.INITIAL_ADMIN_PASSWORD || "";
const INITIAL_ADMIN_NAME = (process.env.INITIAL_ADMIN_NAME || "Occu-Med Owner").trim().slice(0, 160);
const DEFAULT_DOCUMENT_RETENTION_DAYS = Math.min(3650, Math.max(365, Number(process.env.DOCUMENT_RETENTION_DAYS || 2555) || 2555));
const ELECTRONIC_RECORD_CONSENT_TEXT =
  "I agree to use electronic records and electronic signatures for this document and understand that my electronic signature has the same legal effect as a handwritten signature.";

let pool = null;
let dummyPasswordHash = "";
const rateWindows = new Map();

async function initDbPool() {
  const connStr = sanitizeDatabaseUrl(process.env.DATABASE_URL || "");
  if (!connStr) {
    console.warn("DATABASE_URL not set; database operations will fail at runtime");
    return;
  }
  pool = new Pool({
    connectionString: connStr,
    ssl: process.env.NODE_ENV === "production" ? { rejectUnauthorized: false } : false,
  });
  try {
    const client = await pool.connect();
    try {
      await client.query("select 1");
    } finally {
      client.release();
    }
    console.log("neon database connection ok");
  } catch (err) {
    console.error("neon database connection failed:", err.message);
    await pool.end().catch(() => undefined);
    pool = null;
    throw err;
  }
}

async function initDb() {
  if (!pool) return;
  await pool.query("create extension if not exists pgcrypto");
  await pool.query(`
    create table if not exists envelopes (
      id bigint generated by default as identity primary key,
      envelope_id text unique not null,
      status text,
      created_at timestamptz,
      viewed_at timestamptz,
      signed_at timestamptz,
      ip_address text,
      user_agent text,
      viewed_ip text,
      viewed_user_agent text,
      signed_ip text,
      signed_user_agent text,
      pdf_hash text,
      pdf_path text,
      certificate_path text,
      pdf_bytes bytea,
      certificate_bytes bytea,
      occu_med_rep_name text,
      occu_med_rep_title text,
      clinic_rep_name text,
      clinic_rep_title text,
      agreed_electronic boolean,
      recipient_email text,
      payload jsonb,
      updated_at timestamptz not null default now()
    );
  `);
  await pool.query(`
    create table if not exists provider_invitations (
      id bigint generated by default as identity primary key,
      token_hash text unique not null,
      document_type text not null,
      status text not null default 'draft',
      recipient_email text,
      payload jsonb not null,
      completed_payload jsonb,
      created_at timestamptz not null default now(),
      expires_at timestamptz not null,
      viewed_at timestamptz,
      completed_at timestamptz,
      approved_at timestamptz,
      declined_at timestamptz,
      decline_reason text,
      created_ip text,
      created_user_agent text,
      viewed_ip text,
      viewed_user_agent text,
      completed_ip text,
      completed_user_agent text,
      pdf_hash text,
      original_document_hash text,
      signature_hash text,
      evidence_hash text,
      evidence_payload jsonb,
      consent_text text,
      signature_type text,
      pdf_bytes bytea,
      certificate_bytes bytea,
      updated_at timestamptz not null default now()
    );
    create index if not exists provider_invitations_status_idx
      on provider_invitations (status, expires_at);
  `);
  await pool.query(`
    alter table provider_invitations add column if not exists certificate_bytes bytea;
    alter table provider_invitations add column if not exists declined_at timestamptz;
    alter table provider_invitations add column if not exists approved_at timestamptz;
    alter table provider_invitations add column if not exists decline_reason text;
    alter table provider_invitations add column if not exists original_document_hash text;
    alter table provider_invitations add column if not exists signature_hash text;
    alter table provider_invitations add column if not exists evidence_hash text;
    alter table provider_invitations add column if not exists evidence_payload jsonb;
    alter table provider_invitations add column if not exists consent_text text;
    alter table provider_invitations add column if not exists signature_type text;
    alter table provider_invitations add column if not exists created_by_user_id uuid;
    alter table provider_invitations add column if not exists approved_by_user_id uuid;
    alter table provider_invitations add column if not exists cancelled_by_user_id uuid;
    alter table provider_invitations add column if not exists retention_expires_at timestamptz;
    alter table provider_invitations add column if not exists legal_hold boolean not null default false;
    alter table provider_invitations alter column status set default 'draft';
  `);
  await pool.query(`
    create table if not exists provider_invitation_events (
      id bigint generated by default as identity primary key,
      invitation_id bigint not null references provider_invitations(id) on delete cascade,
      event_type text not null,
      details jsonb not null default '{}'::jsonb,
      ip_address text,
      user_agent text,
      previous_hash text,
      event_hash text not null,
      created_at timestamptz not null default now()
    );
    create index if not exists provider_invitation_events_invitation_idx
      on provider_invitation_events (invitation_id, created_at, id);
    create table if not exists admin_users (
      id uuid primary key default gen_random_uuid(),
      email text unique not null,
      display_name text not null,
      password_hash text not null,
      role text not null,
      is_active boolean not null default true,
      last_login_at timestamptz,
      created_by_user_id uuid references admin_users(id),
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now(),
      constraint admin_users_role_check check (role in ('owner','manager','sender','auditor'))
    );
    create table if not exists admin_sessions (
      id bigint generated by default as identity primary key,
      token_hash text unique not null,
      user_id uuid references admin_users(id) on delete cascade,
      created_at timestamptz not null default now(),
      expires_at timestamptz not null,
      last_activity_at timestamptz not null default now(),
      revoked_at timestamptz,
      ip_address text,
      user_agent text
    );
    create index if not exists admin_sessions_active_idx
      on admin_sessions (token_hash, expires_at) where revoked_at is null;
    create table if not exists auth_audit_events (
      id bigint generated by default as identity primary key,
      user_id uuid references admin_users(id) on delete set null,
      actor_user_id uuid references admin_users(id) on delete set null,
      event_type text not null,
      details jsonb not null default '{}'::jsonb,
      ip_address text,
      user_agent text,
      created_at timestamptz not null default now()
    );
    create index if not exists auth_audit_events_created_idx on auth_audit_events (created_at desc);
    create table if not exists retention_settings (
      id smallint primary key default 1 check (id = 1),
      completed_document_days integer not null default 2555,
      inactive_invitation_days integer not null default 365,
      auth_audit_days integer not null default 730,
      updated_by_user_id uuid references admin_users(id) on delete set null,
      updated_at timestamptz not null default now()
    );
    insert into retention_settings (id, completed_document_days, inactive_invitation_days, auth_audit_days)
      values (1, ${DEFAULT_DOCUMENT_RETENTION_DAYS}, 365, 730) on conflict (id) do nothing;
  `);
  await pool.query(`
    alter table admin_sessions add column if not exists user_id uuid references admin_users(id) on delete cascade;
    update admin_sessions set revoked_at = now() where user_id is null and revoked_at is null;
  `);
  dummyPasswordHash = await hashPassword(crypto.randomBytes(32).toString("base64url"));
  const userCount = await pool.query("select count(*)::int as count from admin_users");
  if (Number(userCount.rows[0]?.count || 0) === 0) {
    const bootstrapPasswordError = passwordValidationError(INITIAL_ADMIN_PASSWORD);
    if (INITIAL_ADMIN_EMAIL && !bootstrapPasswordError) {
      await pool.query(
        `insert into admin_users (email, display_name, password_hash, role)
         values ($1,$2,$3,'owner') on conflict (email) do nothing`,
        [INITIAL_ADMIN_EMAIL, INITIAL_ADMIN_NAME, await hashPassword(INITIAL_ADMIN_PASSWORD)],
      );
      console.log("initial owner account created");
    } else {
      console.warn("No admin users exist. Set INITIAL_ADMIN_EMAIL and a compliant INITIAL_ADMIN_PASSWORD once to create the first owner.");
    }
  }
  console.log("database initialized");
}

function newEnvelopeId() {
  const rand = crypto.randomBytes(8).toString("hex").toUpperCase();
  return `${ENVELOPE_PREFIX}-${Date.now().toString(36).toUpperCase()}-${rand}`;
}

function newInvitationToken() {
  return crypto.randomBytes(48).toString("base64url");
}

function tokenHash(token) {
  return crypto.createHash("sha256").update(token).digest("hex");
}

function requireDatabase() {
  if (!pool) throw new Error("Database is not configured");
}

function sha256Hex(bytes) {
  return crypto.createHash("sha256").update(bytes).digest("hex");
}

function canonicalJson(value) {
  if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`;
  if (value && typeof value === "object") {
    return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonicalJson(value[key])}`).join(",")}}`;
  }
  return JSON.stringify(value);
}

function hashJson(value) {
  return sha256Hex(canonicalJson(value));
}

function base64ToUint8(base64) {
  return Uint8Array.from(Buffer.from(base64, "base64"));
}

function limitedText(value, maxLength = 300) {
  return typeof value === "string" ? value.trim().slice(0, maxLength) : "";
}

function buildCompletedProviderData(original, submitted, completedAt) {
  const originalServices = new Map((original.services || []).map((service) => [service.id, service]));
  const services = (submitted.services || []).slice(0, 250).map((service, index) => {
    const originalService = originalServices.get(service?.id);
    return {
      id: originalService?.id || `provider-service-${index + 1}`,
      component: limitedText(service?.component, 300),
      price: limitedText(service?.price, 100),
      source: originalService ? "occu-med" : "provider",
    };
  }).filter((service) => service.component);

  return {
    ...original,
    providerName: limitedText(submitted.providerName) || original.providerName,
    providerContactName: limitedText(submitted.providerContactName),
    providerEmail: limitedText(submitted.providerEmail),
    providerPhone: limitedText(submitted.providerPhone),
    address: {
      street1: limitedText(submitted.address?.street1),
      street2: limitedText(submitted.address?.street2),
      city: limitedText(submitted.address?.city),
      state: limitedText(submitted.address?.state),
      zip: limitedText(submitted.address?.zip, 40),
    },
    services,
    providerSignerName: limitedText(submitted.providerSignerName),
    providerSignerTitle: limitedText(submitted.providerSignerTitle),
    providerSignatureType: submitted.providerSignatureType === "drawn" ? "drawn" : "typed",
    providerSignatureData: submitted.providerSignatureType === "drawn"
      ? limitedText(submitted.providerSignatureData, 500_000)
      : limitedText(submitted.providerSignerName),
    providerSignedDate: completedAt.slice(0, 10),
    agreedElectronic: true,
    electronicConsentText: ELECTRONIC_RECORD_CONSENT_TEXT,
  };
}

function providerChangedServiceTerms(original, completed) {
  const originalServices = (original.services || []).filter((service) => service?.component);
  const completedServices = (completed.services || []).filter((service) => service?.component);
  if (originalServices.length !== completedServices.length) return true;
  const completedById = new Map(completedServices.map((service) => [service.id, service]));
  return originalServices.some((service) => {
    const returned = completedById.get(service.id);
    return !returned || limitedText(returned.component) !== limitedText(service.component)
      || limitedText(returned.price, 100) !== limitedText(service.price, 100);
  });
}

function getClientIp(req) {
  const fwd = req.headers["x-forwarded-for"];
  if (typeof fwd === "string" && fwd.length > 0) return fwd.split(",")[0].trim();
  return req.socket.remoteAddress || "unknown";
}

function allowRequest(req, bucket, limit, windowMs = 60 * 60 * 1000) {
  const now = Date.now();
  if (rateWindows.size > 10_000) {
    for (const [storedKey, value] of rateWindows) {
      if (value.resetAt <= now) rateWindows.delete(storedKey);
    }
  }
  const key = `${bucket}:${getClientIp(req)}`;
  const current = rateWindows.get(key);
  if (!current || current.resetAt <= now) {
    rateWindows.set(key, { count: 1, resetAt: now + windowMs });
    return true;
  }
  if (current.count >= limit) return false;
  current.count += 1;
  return true;
}

function sendJson(res, status, body) {
  res.writeHead(status, {
    "Content-Type": "application/json",
    "Cache-Control": "no-store",
    "X-Content-Type-Options": "nosniff",
    "Referrer-Policy": "no-referrer",
    "Access-Control-Allow-Origin": FRONTEND_ORIGIN,
    "Access-Control-Allow-Headers": "Content-Type, Authorization",
    "Access-Control-Allow-Methods": "GET,POST,OPTIONS",
  });
  res.end(JSON.stringify(body));
}

function sendPdf(res, bytes, filename) {
  res.writeHead(200, {
    "Content-Type": "application/pdf",
    "Content-Disposition": `attachment; filename="${filename.replace(/[^a-z0-9_.-]/gi, "-")}"`,
    "Content-Length": bytes.length,
    "Cache-Control": "no-store",
    "X-Content-Type-Options": "nosniff",
    "Referrer-Policy": "no-referrer",
    "Access-Control-Allow-Origin": FRONTEND_ORIGIN,
    "Access-Control-Allow-Headers": "Content-Type, Authorization",
  });
  res.end(bytes);
}

function sendJsonDownload(res, body, filename) {
  const bytes = Buffer.from(JSON.stringify(body));
  res.writeHead(200, {
    "Content-Type": "application/json",
    "Content-Disposition": `attachment; filename="${filename.replace(/[^a-z0-9_.-]/gi, "-")}"`,
    "Content-Length": bytes.length,
    "Cache-Control": "no-store",
    "X-Content-Type-Options": "nosniff",
    "Referrer-Policy": "no-referrer",
    "Access-Control-Allow-Origin": FRONTEND_ORIGIN,
    "Access-Control-Allow-Headers": "Content-Type, Authorization",
  });
  res.end(bytes);
}

async function createAdminSession(req, userId) {
  const token = crypto.randomBytes(48).toString("base64url");
  const expiresAt = new Date(Date.now() + ADMIN_SESSION_HOURS * 60 * 60 * 1000);
  await pool.query(
    `insert into admin_sessions (token_hash, user_id, expires_at, ip_address, user_agent)
     values ($1,$2,$3,$4,$5)`,
    [tokenHash(token), userId, expiresAt.toISOString(), getClientIp(req), req.headers["user-agent"] || "unknown"],
  );
  return { token, expiresAt: expiresAt.toISOString() };
}

function bearerToken(req) {
  const authorization = typeof req.headers.authorization === "string" ? req.headers.authorization : "";
  return authorization.startsWith("Bearer ") ? authorization.slice(7).trim() : "";
}

async function adminSession(req) {
  const token = bearerToken(req);
  if (!token || !pool) return null;
  const { rows } = await pool.query(
    `select s.id, s.user_id, s.expires_at, s.last_activity_at,
            u.email, u.display_name, u.role, u.is_active, u.last_login_at, u.created_at
       from admin_sessions s
       join admin_users u on u.id = s.user_id
      where s.token_hash = $1 and s.revoked_at is null and s.expires_at > now()
        and u.is_active = true limit 1`,
    [tokenHash(token)],
  );
  if (!rows.length) return null;
  const idleMs = Date.now() - new Date(rows[0].last_activity_at).getTime();
  if (idleMs > ADMIN_IDLE_MINUTES * 60 * 1000) {
    await pool.query("update admin_sessions set revoked_at = now() where id = $1", [rows[0].id]);
    return null;
  }
  await pool.query("update admin_sessions set last_activity_at = now() where id = $1", [rows[0].id]);
  return rows[0];
}

async function requireAdminAccess(req, res, permission = "view_documents") {
  const session = await adminSession(req);
  if (!session) {
    sendJson(res, 401, { error: "Your admin session is invalid or has expired." });
    return false;
  }
  if (permission && !hasPermission(session.role, permission)) {
    sendJson(res, 403, { error: "Your account does not have permission for this action." });
    return false;
  }
  return session;
}

async function logAuthEvent(eventType, req, { userId = null, actorUserId = null, details = {} } = {}) {
  if (!pool) return;
  await pool.query(
    `insert into auth_audit_events (user_id, actor_user_id, event_type, details, ip_address, user_agent)
     values ($1,$2,$3,$4,$5,$6)`,
    [userId, actorUserId, eventType, JSON.stringify(details), getClientIp(req), req.headers["user-agent"] || "unknown"],
  );
}

async function logInvitationEvent(invitationId, eventType, req, details = {}) {
  const { rows } = await pool.query(
    "select event_hash from provider_invitation_events where invitation_id = $1 order by id desc limit 1",
    [invitationId],
  );
  const createdAt = new Date().toISOString();
  const previousHash = rows[0]?.event_hash || null;
  const entry = {
    invitationId: String(invitationId),
    eventType,
    details,
    ipAddress: getClientIp(req),
    userAgent: req.headers["user-agent"] || "unknown",
    createdAt,
    previousHash,
  };
  const eventHash = hashJson(entry);
  await pool.query(
    `insert into provider_invitation_events
      (invitation_id, event_type, details, ip_address, user_agent, previous_hash, event_hash, created_at)
     values ($1,$2,$3,$4,$5,$6,$7,$8)`,
    [invitationId, eventType, JSON.stringify(details), entry.ipAddress, entry.userAgent, previousHash, eventHash, createdAt],
  );
  return eventHash;
}

function verifyInvitationEvidence(row) {
  const originalDocumentHashValid = row.original_document_hash
    ? hashJson(row.payload) === row.original_document_hash
    : null;
  const finalPdfHashValid = row.pdf_hash && row.pdf_bytes
    ? sha256Hex(row.pdf_bytes) === row.pdf_hash
    : null;
  let evidenceHashValid = null;
  if (row.evidence_hash && row.evidence_payload && row.completed_payload && row.signature_hash && row.completed_ip) {
    const completedPayloadHashValid = hashJson(row.completed_payload) === row.evidence_payload.completedPayloadHash;
    const signatureDataHash = sha256Hex(row.completed_payload.providerSignatureData || row.completed_payload.providerSignerName);
    const expectedSignatureHash = hashJson({
      signatureType: row.completed_payload.providerSignatureType,
      signatureDataHash,
      fullName: row.completed_payload.providerSignerName,
      ipAddress: row.completed_ip,
      originalDocumentHash: row.original_document_hash,
    });
    const signatureHashValid = expectedSignatureHash === row.signature_hash
      && row.evidence_payload.signatureHash === row.signature_hash;
    evidenceHashValid = hashJson(row.evidence_payload) === row.evidence_hash
      && completedPayloadHashValid
      && signatureHashValid;
  }
  return {
    valid: originalDocumentHashValid === true && finalPdfHashValid === true && evidenceHashValid === true,
    originalDocumentHashValid,
    finalPdfHashValid,
    evidenceHashValid,
  };
}

function verifyEventChain(invitationId, eventRows) {
  let previousEventHash = null;
  let valid = eventRows.length > 0;
  const events = eventRows.map((event) => {
    const createdAt = new Date(event.created_at).toISOString();
    const expectedHash = hashJson({
      invitationId: String(invitationId),
      eventType: event.event_type,
      details: event.details,
      ipAddress: event.ip_address,
      userAgent: event.user_agent,
      createdAt,
      previousHash: previousEventHash,
    });
    if (event.previous_hash !== previousEventHash || event.event_hash !== expectedHash) valid = false;
    previousEventHash = event.event_hash;
    return {
      eventType: event.event_type,
      details: event.details,
      ipAddress: event.ip_address,
      userAgent: event.user_agent,
      previousHash: event.previous_hash || undefined,
      eventHash: event.event_hash,
      createdAt,
    };
  });
  return { valid, events };
}

function adminInvitationRow(row, includeData = false) {
  const data = row.completed_payload || row.payload || {};
  const result = {
    id: String(row.id),
    documentType: row.document_type,
    status: row.status,
    providerName: data.providerName || "Unnamed provider",
    documentNumber: data.documentNumber || `Invitation ${row.id}`,
    recipientEmail: row.recipient_email || data.providerEmail || "",
    createdAt: row.created_at,
    expiresAt: row.expires_at,
    viewedAt: row.viewed_at || undefined,
    completedAt: row.completed_at || undefined,
    approvedAt: row.approved_at || undefined,
    declinedAt: row.declined_at || undefined,
    declineReason: row.decline_reason || undefined,
    legalHold: Boolean(row.legal_hold),
    retentionExpiresAt: row.retention_expires_at || undefined,
    hasCompletedDocument: Boolean(row.pdf_bytes),
  };
  if (includeData) {
    result.data = data;
    result.originalData = row.payload || {};
    result.pdfHash = row.pdf_hash || undefined;
    result.originalDocumentHash = row.original_document_hash || undefined;
    result.evidenceHash = row.evidence_hash || undefined;
    result.signatureHash = row.signature_hash || undefined;
    result.signatureType = row.signature_type || undefined;
    result.consentText = row.consent_text || undefined;
    result.verification = verifyInvitationEvidence(row);
  }
  return result;
}

function readJson(req) {
  return new Promise((resolve, reject) => {
    let raw = "";
    req.on("data", (chunk) => {
      raw += chunk;
      if (raw.length > 12_000_000) {
        reject(new Error("Payload too large"));
        req.destroy();
      }
    });
    req.on("end", () => {
      try {
        resolve(raw ? JSON.parse(raw) : {});
      } catch (e) {
        reject(e);
      }
    });
    req.on("error", reject);
  });
}


async function maybeSendEmail({ to, envelopeId, pdfHash, pdfBytes, certBytes }) {
  const apiKey = process.env.RESEND_API_KEY;
  const from = process.env.MAIL_FROM;
  if (!to || !apiKey || !from) return;

  await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from,
      to,
      subject: `Completed Occu-Med Provider Service Agreement ${envelopeId}`,
      text: `Provider Service Agreement ${envelopeId} has been finalized.\nSHA-256: ${pdfHash}`,
      attachments: [
        { filename: `${envelopeId}-signed.pdf`, content: Buffer.from(pdfBytes).toString("base64") },
        { filename: `${envelopeId}-certificate.pdf`, content: Buffer.from(certBytes).toString("base64") },
      ],
    }),
  });
}

async function sendMemoEmail({ to, subject, text, pdfBytes, filename }) {
  const apiKey = process.env.RESEND_API_KEY;
  const from = process.env.MAIL_FROM;
  if (!to || !apiKey || !from) {
    throw new Error("Email provider not configured");
  }

  const response = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from,
      to,
      subject,
      text,
      attachments: [
        { filename, content: Buffer.from(pdfBytes).toString("base64") },
      ],
    }),
  });

  if (!response.ok) {
    const details = await response.text();
    throw new Error(`Resend send failed (${response.status}): ${details}`);
  }
}

async function maybeSendCompletedProviderDocument({ data, recipientEmail, pdfBytes, certificateBytes }) {
  const apiKey = process.env.RESEND_API_KEY;
  const from = process.env.MAIL_FROM;
  if (!apiKey || !from) return false;
  const recipients = [...new Set([PROVIDER_RESPONSES_TO, recipientEmail || data.providerEmail].filter(Boolean))];
  if (!recipients.length) return false;

  const label = data.documentType === "fee-proposal" ? "Provider Fee Proposal" : "Provider Service Agreement";
  const response = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      from,
      to: recipients,
      subject: `Completed Occu-Med ${label} - ${data.providerName}`,
      text: `${data.providerName} completed document ${data.documentNumber}. The completed document and audit certificate are attached.`,
      attachments: [
        { filename: `${data.documentNumber}-completed.pdf`, content: Buffer.from(pdfBytes).toString("base64") },
        { filename: `${data.documentNumber}-certificate.pdf`, content: Buffer.from(certificateBytes).toString("base64") },
      ],
    }),
  });
  if (!response.ok) throw new Error(`Completed-document email failed (${response.status}): ${await response.text()}`);
  return true;
}

async function maybeSendProviderChangesForReview({ data, pdfBytes, certificateBytes }) {
  const apiKey = process.env.RESEND_API_KEY;
  const from = process.env.MAIL_FROM;
  if (!apiKey || !from || !PROVIDER_RESPONSES_TO) return false;

  const label = data.documentType === "fee-proposal" ? "Provider Fee Proposal" : "Provider Service Agreement";
  const response = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      from,
      to: [PROVIDER_RESPONSES_TO],
      subject: `Provider changes need review - ${data.providerName}`,
      text: `${data.providerName} returned ${label} ${data.documentNumber} with service or fee changes. Review and approve the returned terms in the Occu-Med admin workspace.`,
      attachments: [
        { filename: `${data.documentNumber}-returned.pdf`, content: Buffer.from(pdfBytes).toString("base64") },
        { filename: `${data.documentNumber}-pending-certificate.pdf`, content: Buffer.from(certificateBytes).toString("base64") },
      ],
    }),
  });
  if (!response.ok) throw new Error(`Provider-review email failed (${response.status}): ${await response.text()}`);
  return true;
}

async function getEnvelope(envelopeId) {
  const { rows } = await pool.query(
    "select envelope_id, created_at, viewed_at from envelopes where envelope_id = $1",
    [envelopeId]
  );
  return rows.length > 0 ? rows[0] : null;
}

const server = http.createServer(async (req, res) => {
  if (req.method === "OPTIONS") {
    res.writeHead(204, {
      "Access-Control-Allow-Origin": FRONTEND_ORIGIN,
      "Access-Control-Allow-Headers": "Content-Type, Authorization",
      "Access-Control-Allow-Methods": "GET,POST,OPTIONS",
    });
    return res.end();
  }

  const url = new URL(req.url || "/", `http://${req.headers.host}`);

  try {
    if (req.method === "GET" && url.pathname === "/health") {
      return sendJson(res, 200, { ok: true, databaseConfigured: Boolean(pool), service: "occu-med-backend", timestamp: new Date().toISOString() });
    }

    const verificationMatch = url.pathname.match(/^\/api\/verify\/([0-9a-f]{64})$/i);
    if (req.method === "GET" && verificationMatch) {
      if (!allowRequest(req, "public-verification", 120, 60 * 60 * 1000)) {
        return sendJson(res, 429, { error: "Too many verification requests. Please try again later." });
      }
      requireDatabase();
      const { rows } = await pool.query(
        `select id, document_type, status, payload, completed_payload, created_at, completed_at, approved_at,
                pdf_hash, pdf_bytes, original_document_hash, signature_hash, evidence_hash,
                evidence_payload, signature_type, completed_ip
           from provider_invitations where evidence_hash = $1 limit 1`,
        [verificationMatch[1].toLowerCase()],
      );
      if (!rows.length) return sendJson(res, 404, { error: "No certificate matches this evidence code." });
      const row = rows[0];
      const eventResult = await pool.query(
        `select event_type, details, ip_address, user_agent, previous_hash, event_hash, created_at
           from provider_invitation_events where invitation_id = $1 order by id asc`,
        [row.id],
      );
      const evidence = verifyInvitationEvidence(row);
      const chain = verifyEventChain(row.id, eventResult.rows);
      const data = row.completed_payload || row.payload || {};
      const verified = row.status === "completed" && evidence.valid && chain.valid;
      return sendJson(res, 200, {
        verified,
        status: row.status,
        documentType: row.document_type,
        documentNumber: data.documentNumber,
        providerName: data.providerName,
        signerName: data.providerSignerName,
        signatureType: row.signature_type,
        signedAt: row.completed_at,
        approvedAt: row.approved_at || undefined,
        finalPdfHash: row.pdf_hash,
        evidenceHash: row.evidence_hash,
        checks: {
          originalDocument: evidence.originalDocumentHashValid,
          finalPdf: evidence.finalPdfHashValid,
          signatureEvidence: evidence.evidenceHashValid,
          auditChain: chain.valid,
        },
      });
    }

    if (req.method === "POST" && url.pathname === "/api/admin/session") {
      requireDatabase();
      const body = await readJson(req);
      const email = normalizeEmail(body?.email);
      if (!allowRequest(req, `admin-login:${sha256Hex(email).slice(0, 16)}`, 8, 15 * 60 * 1000)) {
        return sendJson(res, 429, { error: "Too many sign-in attempts. Please try again in 15 minutes." });
      }
      const result = email
        ? await pool.query(
          `select id, email, display_name, password_hash, role, is_active, last_login_at, created_at
             from admin_users where email = $1 limit 1`,
          [email],
        )
        : { rows: [] };
      const user = result.rows[0];
      const passwordValid = await verifyPassword(String(body?.password || ""), user?.password_hash || dummyPasswordHash);
      if (!user || !user.is_active || !passwordValid) {
        await logAuthEvent("login_failed", req, { userId: user?.id || null, details: { email } });
        return sendJson(res, 401, { error: "The email or password is incorrect." });
      }
      await pool.query("delete from admin_sessions where expires_at < now() or revoked_at < now() - interval '1 day'");
      const session = await createAdminSession(req, user.id);
      await pool.query("update admin_users set last_login_at = now(), updated_at = now() where id = $1", [user.id]);
      await logAuthEvent("login_succeeded", req, { userId: user.id, actorUserId: user.id });
      return sendJson(res, 201, {
        ok: true,
        ...session,
        idleMinutes: ADMIN_IDLE_MINUTES,
        user: publicAdminUser({ ...user, last_login_at: new Date().toISOString() }),
      });
    }

    if (req.method === "GET" && url.pathname === "/api/admin/session") {
      const session = await requireAdminAccess(req, res);
      if (!session) return;
      return sendJson(res, 200, { ok: true, idleMinutes: ADMIN_IDLE_MINUTES, user: publicAdminUser(session) });
    }

    if (req.method === "POST" && url.pathname === "/api/admin/logout") {
      requireDatabase();
      const token = bearerToken(req);
      const session = token ? await adminSession(req) : null;
      if (token) await pool.query("update admin_sessions set revoked_at = now() where token_hash = $1", [tokenHash(token)]);
      if (session) await logAuthEvent("logout", req, { userId: session.user_id, actorUserId: session.user_id });
      return sendJson(res, 200, { ok: true });
    }

    if (req.method === "GET" && url.pathname === "/api/admin/users") {
      const session = await requireAdminAccess(req, res, "manage_users");
      if (!session) return;
      const { rows } = await pool.query(
        `select id, email, display_name, role, is_active, last_login_at, created_at
           from admin_users order by is_active desc, display_name asc`,
      );
      return sendJson(res, 200, { users: rows.map(publicAdminUser), roles: ADMIN_ROLES });
    }

    if (req.method === "POST" && url.pathname === "/api/admin/users") {
      const session = await requireAdminAccess(req, res, "manage_users");
      if (!session) return;
      const body = await readJson(req);
      const email = normalizeEmail(body?.email);
      const displayName = limitedText(body?.displayName, 160);
      const role = ADMIN_ROLES.includes(body?.role) ? body.role : "";
      const passwordError = passwordValidationError(body?.password);
      if (!email || !email.includes("@") || !displayName || !role || passwordError) {
        return sendJson(res, 400, { error: passwordError || "Name, valid email, and role are required." });
      }
      try {
        const { rows } = await pool.query(
          `insert into admin_users (email, display_name, password_hash, role, created_by_user_id)
           values ($1,$2,$3,$4,$5)
           returning id, email, display_name, role, is_active, last_login_at, created_at`,
          [email, displayName, await hashPassword(body.password), role, session.user_id],
        );
        await logAuthEvent("user_created", req, {
          userId: rows[0].id, actorUserId: session.user_id, details: { email, role },
        });
        return sendJson(res, 201, { user: publicAdminUser(rows[0]) });
      } catch (error) {
        if (error?.code === "23505") return sendJson(res, 409, { error: "An account already uses that email address." });
        throw error;
      }
    }

    const adminUserMatch = url.pathname.match(/^\/api\/admin\/users\/([0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})$/i);
    if (req.method === "POST" && adminUserMatch) {
      const session = await requireAdminAccess(req, res, "manage_users");
      if (!session) return;
      const body = await readJson(req);
      const existingResult = await pool.query(
        `select id, email, display_name, password_hash, role, is_active, last_login_at, created_at
           from admin_users where id = $1`,
        [adminUserMatch[1]],
      );
      if (!existingResult.rows.length) return sendJson(res, 404, { error: "Account not found." });
      const existing = existingResult.rows[0];
      const nextRole = body?.role === undefined ? existing.role : (ADMIN_ROLES.includes(body.role) ? body.role : "");
      const nextActive = body?.active === undefined ? existing.is_active : Boolean(body.active);
      const nextName = body?.displayName === undefined ? existing.display_name : limitedText(body.displayName, 160);
      if (!nextRole || !nextName) return sendJson(res, 400, { error: "A valid name and role are required." });
      if (existing.role === "owner" && existing.is_active && (nextRole !== "owner" || !nextActive)) {
        const ownerCount = await pool.query("select count(*)::int as count from admin_users where role = 'owner' and is_active = true");
        if (Number(ownerCount.rows[0].count) <= 1) return sendJson(res, 409, { error: "The last active owner cannot be disabled or assigned another role." });
      }
      let passwordHash = existing.password_hash;
      if (body?.password) {
        const passwordError = passwordValidationError(body.password);
        if (passwordError) return sendJson(res, 400, { error: passwordError });
        passwordHash = await hashPassword(body.password);
      }
      const { rows } = await pool.query(
        `update admin_users set display_name = $2, role = $3, is_active = $4,
           password_hash = $5, updated_at = now() where id = $1
         returning id, email, display_name, role, is_active, last_login_at, created_at`,
        [existing.id, nextName, nextRole, nextActive, passwordHash],
      );
      if (!nextActive || body?.password || nextRole !== existing.role) {
        await pool.query("update admin_sessions set revoked_at = now() where user_id = $1 and revoked_at is null", [existing.id]);
      }
      await logAuthEvent("user_updated", req, {
        userId: existing.id,
        actorUserId: session.user_id,
        details: { role: nextRole, active: nextActive, passwordReset: Boolean(body?.password) },
      });
      return sendJson(res, 200, { user: publicAdminUser(rows[0]) });
    }

    if (req.method === "POST" && url.pathname === "/api/admin/account/password") {
      const session = await requireAdminAccess(req, res, null);
      if (!session) return;
      const body = await readJson(req);
      const passwordError = passwordValidationError(body?.newPassword);
      if (passwordError) return sendJson(res, 400, { error: passwordError });
      const { rows } = await pool.query("select password_hash from admin_users where id = $1", [session.user_id]);
      if (!rows.length || !await verifyPassword(String(body?.currentPassword || ""), rows[0].password_hash)) {
        return sendJson(res, 401, { error: "The current password is incorrect." });
      }
      await pool.query("update admin_users set password_hash = $2, updated_at = now() where id = $1", [session.user_id, await hashPassword(body.newPassword)]);
      await pool.query(
        "update admin_sessions set revoked_at = now() where user_id = $1 and token_hash <> $2 and revoked_at is null",
        [session.user_id, tokenHash(bearerToken(req))],
      );
      await logAuthEvent("password_changed", req, { userId: session.user_id, actorUserId: session.user_id });
      return sendJson(res, 200, { ok: true });
    }

    if (req.method === "GET" && url.pathname === "/api/admin/security-audit") {
      const session = await requireAdminAccess(req, res, "view_security_audit");
      if (!session) return;
      const { rows } = await pool.query(
        `select a.event_type, a.details, a.ip_address, a.user_agent, a.created_at,
                u.email, actor.email as actor_email
           from auth_audit_events a
           left join admin_users u on u.id = a.user_id
           left join admin_users actor on actor.id = a.actor_user_id
          order by a.id desc limit 250`,
      );
      return sendJson(res, 200, { events: rows.map((row) => ({
        eventType: row.event_type,
        details: row.details,
        email: row.email || undefined,
        actorEmail: row.actor_email || undefined,
        ipAddress: row.ip_address || undefined,
        userAgent: row.user_agent || undefined,
        createdAt: row.created_at,
      })) });
    }

    if (req.method === "GET" && url.pathname === "/api/admin/retention") {
      const session = await requireAdminAccess(req, res, "manage_retention");
      if (!session) return;
      const settings = await pool.query("select * from retention_settings where id = 1");
      const row = settings.rows[0];
      const counts = await pool.query(
        `select
          count(*) filter (where status = 'completed' and completed_at < now() - ($1::text || ' days')::interval and legal_hold = false)::int as completed_eligible,
          count(*) filter (where status in ('declined','expired','cancelled') and updated_at < now() - ($2::text || ' days')::interval and legal_hold = false)::int as inactive_eligible,
          count(*) filter (where legal_hold = true)::int as legal_holds
         from provider_invitations`,
        [row.completed_document_days, row.inactive_invitation_days],
      );
      return sendJson(res, 200, {
        completedDocumentDays: row.completed_document_days,
        inactiveInvitationDays: row.inactive_invitation_days,
        authAuditDays: row.auth_audit_days,
        updatedAt: row.updated_at,
        preview: {
          completedEligible: counts.rows[0].completed_eligible,
          inactiveEligible: counts.rows[0].inactive_eligible,
          legalHolds: counts.rows[0].legal_holds,
        },
      });
    }

    if (req.method === "POST" && url.pathname === "/api/admin/retention") {
      const session = await requireAdminAccess(req, res, "manage_retention");
      if (!session) return;
      const body = await readJson(req);
      const completedDays = Math.min(3650, Math.max(365, Number(body?.completedDocumentDays) || 2555));
      const inactiveDays = Math.min(3650, Math.max(30, Number(body?.inactiveInvitationDays) || 365));
      const auditDays = Math.min(3650, Math.max(90, Number(body?.authAuditDays) || 730));
      await pool.query(
        `update retention_settings set completed_document_days = $1, inactive_invitation_days = $2,
           auth_audit_days = $3, updated_by_user_id = $4, updated_at = now() where id = 1`,
        [completedDays, inactiveDays, auditDays, session.user_id],
      );
      await logAuthEvent("retention_policy_updated", req, {
        actorUserId: session.user_id, details: { completedDays, inactiveDays, auditDays },
      });
      return sendJson(res, 200, { ok: true });
    }

    if (req.method === "GET" && url.pathname === "/api/admin/backups/export") {
      const session = await requireAdminAccess(req, res, "export_backups");
      if (!session) return;
      const invitationResult = await pool.query("select * from provider_invitations order by id asc");
      const eventResult = await pool.query("select * from provider_invitation_events order by id asc");
      const exportedAt = new Date().toISOString();
      const invitations = invitationResult.rows.map((row) => ({
        ...row,
        pdf_bytes: row.pdf_bytes ? row.pdf_bytes.toString("base64") : null,
        certificate_bytes: row.certificate_bytes ? row.certificate_bytes.toString("base64") : null,
      }));
      const snapshot = { version: 1, exportedAt, invitations, invitationEvents: eventResult.rows };
      const backup = { ...snapshot, manifestSha256: hashJson(snapshot) };
      await logAuthEvent("backup_exported", req, {
        actorUserId: session.user_id,
        details: { invitationCount: invitations.length, manifestSha256: backup.manifestSha256 },
      });
      return sendJsonDownload(res, backup, `occu-med-provider-documents-${exportedAt.slice(0, 10)}.json`);
    }

    if (req.method === "GET" && url.pathname === "/api/admin/provider-invitations") {
      if (!await requireAdminAccess(req, res)) return;
      requireDatabase();
      await pool.query(
        `update provider_invitations set status = 'expired', updated_at = now(),
           retention_expires_at = now() + make_interval(days => coalesce(
             (select inactive_invitation_days from retention_settings where id = 1), 365
           ))
         where status in ('draft','sent','viewed') and expires_at < now()`,
      );
      const allowedStatuses = new Set(["draft", "sent", "viewed", "returned", "completed", "declined", "expired", "cancelled"]);
      const status = allowedStatuses.has(url.searchParams.get("status")) ? url.searchParams.get("status") : "";
      const query = limitedText(url.searchParams.get("q"), 120);
      const likeQuery = `%${query}%`;
      const { rows } = await pool.query(
        `select id, document_type, status, recipient_email, payload, completed_payload,
                created_at, expires_at, viewed_at, completed_at, approved_at, declined_at, decline_reason,
                pdf_bytes, legal_hold, retention_expires_at
           from provider_invitations
          where ($1 = '' or status = $1)
            and ($2 = '' or recipient_email ilike $3
              or coalesce(completed_payload, payload)->>'providerName' ilike $3
              or coalesce(completed_payload, payload)->>'documentNumber' ilike $3)
          order by created_at desc
          limit 200`,
        [status, query, likeQuery],
      );
      const countResult = await pool.query(
        `select status, count(*)::int as count from provider_invitations group by status`,
      );
      const counts = { all: 0, draft: 0, sent: 0, viewed: 0, returned: 0, completed: 0, declined: 0, expired: 0, cancelled: 0 };
      for (const row of countResult.rows) {
        if (Object.hasOwn(counts, row.status)) counts[row.status] = Number(row.count);
        counts.all += Number(row.count);
      }
      return sendJson(res, 200, { items: rows.map((row) => adminInvitationRow(row)), counts });
    }

    const adminInvitationMatch = url.pathname.match(/^\/api\/admin\/provider-invitations\/(\d+)$/);
    if (req.method === "GET" && adminInvitationMatch) {
      if (!await requireAdminAccess(req, res)) return;
      requireDatabase();
      const { rows } = await pool.query(
        `select id, document_type, status, recipient_email, payload, completed_payload,
                created_at, expires_at, viewed_at, completed_at, approved_at, declined_at, decline_reason,
                pdf_hash, pdf_bytes, original_document_hash, signature_hash, evidence_hash,
                evidence_payload, consent_text, signature_type, completed_ip, legal_hold, retention_expires_at
           from provider_invitations where id = $1`,
        [adminInvitationMatch[1]],
      );
      if (!rows.length) return sendJson(res, 404, { error: "Invitation not found." });
      const eventResult = await pool.query(
        `select event_type, details, ip_address, user_agent, previous_hash, event_hash, created_at
           from provider_invitation_events where invitation_id = $1 order by id asc`,
        [adminInvitationMatch[1]],
      );
      const chain = verifyEventChain(adminInvitationMatch[1], eventResult.rows);
      const invitation = adminInvitationRow(rows[0], true);
      const verification = {
        ...invitation.verification,
        auditChainValid: chain.valid,
        valid: invitation.verification.valid && chain.valid,
      };
      return sendJson(res, 200, {
        ...invitation,
        verification,
        events: chain.events,
      });
    }

    const adminResendMatch = url.pathname.match(/^\/api\/admin\/provider-invitations\/(\d+)\/resend$/);
    if (req.method === "POST" && adminResendMatch) {
      const session = await requireAdminAccess(req, res, "manage_invitations");
      if (!session) return;
      requireDatabase();
      const { rows } = await pool.query(
        "select status from provider_invitations where id = $1",
        [adminResendMatch[1]],
      );
      if (!rows.length) return sendJson(res, 404, { error: "Invitation not found." });
      if (rows[0].status === "completed") return sendJson(res, 409, { error: "A completed invitation cannot be resent." });
      if (rows[0].status === "cancelled") return sendJson(res, 409, { error: "A cancelled invitation cannot be resent." });
      if (rows[0].status === "declined") return sendJson(res, 409, { error: "A declined invitation cannot be resent. Create a revised document instead." });
      if (rows[0].status === "returned") return sendJson(res, 409, { error: "Review the provider's returned changes before taking another action." });
      const token = newInvitationToken();
      const expiresAt = new Date(Date.now() + INVITATION_TTL_DAYS * 24 * 60 * 60 * 1000);
      await pool.query(
        `update provider_invitations set token_hash = $2, status = 'draft', expires_at = $3,
          viewed_at = null, viewed_ip = null, viewed_user_agent = null, updated_at = now() where id = $1`,
        [adminResendMatch[1], tokenHash(token), expiresAt.toISOString()],
      );
      const providerPath = `/provider/${token}`;
      await logInvitationEvent(adminResendMatch[1], "link_rotated", req, {
        expiresAt: expiresAt.toISOString(), actorUserId: session.user_id,
      });
      return sendJson(res, 200, { providerPath, expiresAt: expiresAt.toISOString(), status: "draft" });
    }

    const adminMarkSentMatch = url.pathname.match(/^\/api\/admin\/provider-invitations\/(\d+)\/mark-sent$/);
    if (req.method === "POST" && adminMarkSentMatch) {
      const session = await requireAdminAccess(req, res, "manage_invitations");
      if (!session) return;
      requireDatabase();
      const body = await readJson(req);
      const recipientEmail = normalizeEmail(body?.recipientEmail);
      const cc = limitedText(body?.cc, 1_000);
      const subject = limitedText(body?.subject, 300);
      if (!recipientEmail || !recipientEmail.includes("@") || !subject) {
        return sendJson(res, 400, { error: "Recipient email and subject are required before marking the invitation as sent." });
      }
      const result = await pool.query(
        `update provider_invitations set status = case when status = 'draft' then 'sent' else status end,
           recipient_email = $2, updated_at = now()
         where id = $1 and status in ('draft','sent','viewed')
         returning id, status`,
        [adminMarkSentMatch[1], recipientEmail],
      );
      if (!result.rowCount) return sendJson(res, 409, { error: "This invitation can no longer be marked as sent." });
      await logInvitationEvent(adminMarkSentMatch[1], "manual_send_confirmed", req, {
        actorUserId: session.user_id,
        senderName: session.display_name,
        senderEmail: session.email,
        recipientEmail,
        cc: cc || null,
        subject,
        deliveryMethod: "outlook-manual",
      });
      return sendJson(res, 200, { ok: true, status: result.rows[0].status, recipientEmail });
    }

    const adminApproveMatch = url.pathname.match(/^\/api\/admin\/provider-invitations\/(\d+)\/approve$/);
    if (req.method === "POST" && adminApproveMatch) {
      const session = await requireAdminAccess(req, res, "approve_terms");
      if (!session) return;
      requireDatabase();
      const { rows } = await pool.query(
        `select id, status, recipient_email, completed_payload, created_at, viewed_at, completed_at,
                completed_ip, completed_user_agent, pdf_hash, pdf_bytes, original_document_hash,
                signature_type, signature_hash, evidence_hash, consent_text
           from provider_invitations where id = $1`,
        [adminApproveMatch[1]],
      );
      if (!rows.length) return sendJson(res, 404, { error: "Invitation not found." });
      if (rows[0].status !== "returned") return sendJson(res, 409, { error: "Only returned provider changes can be approved." });
      const approvedAt = new Date().toISOString();
      const data = rows[0].completed_payload;
      const certificateBytes = await generateCertificatePdf({
        envelopeId: data.documentNumber,
        pdfHash: rows[0].pdf_hash,
        audit: {
          createdAt: new Date(rows[0].created_at).toISOString(),
          viewedAt: rows[0].viewed_at ? new Date(rows[0].viewed_at).toISOString() : "—",
          signedAt: new Date(rows[0].completed_at).toISOString(),
          approvedAt,
          reviewStatus: "Provider changes approved by Occu-Med",
          ipAddress: rows[0].completed_ip,
          userAgent: rows[0].completed_user_agent,
          occuMedRepName: data.preparedBy || "Occu-Med",
          clinicRepFullName: data.providerSignerName,
          agreedElectronic: true,
          originalDocumentHash: rows[0].original_document_hash,
          signatureType: rows[0].signature_type,
          signatureHash: rows[0].signature_hash,
          evidenceHash: rows[0].evidence_hash,
          verificationUrl: FRONTEND_APP_URL ? `${FRONTEND_APP_URL}/verify` : undefined,
          consentText: rows[0].consent_text,
        },
      });
      const result = await pool.query(
        `update provider_invitations set status = 'completed', approved_at = $2,
          certificate_bytes = $3, approved_by_user_id = $4,
          retention_expires_at = now() + make_interval(days => coalesce(
            (select completed_document_days from retention_settings where id = 1), 2555
          )),
          updated_at = now()
         where id = $1 and status = 'returned' returning id`,
        [adminApproveMatch[1], approvedAt, Buffer.from(certificateBytes), session.user_id],
      );
      if (!result.rowCount) return sendJson(res, 409, { error: "The invitation status changed before approval." });
      await logInvitationEvent(adminApproveMatch[1], "provider_changes_approved", req, { approvedAt, actorUserId: session.user_id });
      let emailSent = false;
      try {
        emailSent = await maybeSendCompletedProviderDocument({
          data,
          recipientEmail: rows[0].recipient_email,
          pdfBytes: rows[0].pdf_bytes,
          certificateBytes,
        });
      } catch (error) {
        console.error("approved provider document email failed", error);
      }
      return sendJson(res, 200, { ok: true, status: "completed", approvedAt, emailSent });
    }

    const adminCancelMatch = url.pathname.match(/^\/api\/admin\/provider-invitations\/(\d+)\/cancel$/);
    if (req.method === "POST" && adminCancelMatch) {
      const session = await requireAdminAccess(req, res, "manage_invitations");
      if (!session) return;
      requireDatabase();
      const result = await pool.query(
        `update provider_invitations set status = 'cancelled', cancelled_by_user_id = $2,
           retention_expires_at = now() + make_interval(days => coalesce(
             (select inactive_invitation_days from retention_settings where id = 1), 365
           )),
           updated_at = now() where id = $1 and status not in ('completed','declined','cancelled') returning id`,
        [adminCancelMatch[1], session.user_id],
      );
      if (!result.rowCount) return sendJson(res, 409, { error: "Only an active invitation can be cancelled." });
      await logInvitationEvent(adminCancelMatch[1], "cancelled", req, { actorUserId: session.user_id });
      return sendJson(res, 200, { ok: true, status: "cancelled" });
    }

    const adminLegalHoldMatch = url.pathname.match(/^\/api\/admin\/provider-invitations\/(\d+)\/legal-hold$/);
    if (req.method === "POST" && adminLegalHoldMatch) {
      const session = await requireAdminAccess(req, res, "manage_retention");
      if (!session) return;
      const body = await readJson(req);
      const active = Boolean(body?.active);
      const result = await pool.query(
        "update provider_invitations set legal_hold = $2, updated_at = now() where id = $1 returning id",
        [adminLegalHoldMatch[1], active],
      );
      if (!result.rowCount) return sendJson(res, 404, { error: "Invitation not found." });
      await logInvitationEvent(adminLegalHoldMatch[1], active ? "legal_hold_applied" : "legal_hold_released", req, { actorUserId: session.user_id });
      await logAuthEvent(active ? "legal_hold_applied" : "legal_hold_released", req, {
        actorUserId: session.user_id, details: { invitationId: adminLegalHoldMatch[1] },
      });
      return sendJson(res, 200, { ok: true, legalHold: active });
    }

    const adminFileMatch = url.pathname.match(/^\/api\/admin\/provider-invitations\/(\d+)\/(document|certificate)$/);
    if (req.method === "GET" && adminFileMatch) {
      const session = await requireAdminAccess(req, res, "download_documents");
      if (!session) return;
      requireDatabase();
      const column = adminFileMatch[2] === "document" ? "pdf_bytes" : "certificate_bytes";
      const { rows } = await pool.query(
        `select ${column} as bytes, coalesce(completed_payload, payload)->>'documentNumber' as document_number
           from provider_invitations where id = $1`,
        [adminFileMatch[1]],
      );
      if (!rows.length || !rows[0].bytes) return sendJson(res, 404, { error: "The completed file is not available." });
      await logInvitationEvent(adminFileMatch[1], `${adminFileMatch[2]}_downloaded`, req, { actorUserId: session.user_id });
      return sendPdf(res, rows[0].bytes, `${rows[0].document_number || "provider-document"}-${adminFileMatch[2]}.pdf`);
    }

    if (req.method === "POST" && url.pathname === "/api/provider-invitations") {
      if (!allowRequest(req, "provider-invitation-create", 30)) {
        return sendJson(res, 429, { error: "Too many invitations created. Please try again later." });
      }
      const session = await requireAdminAccess(req, res, "create_documents");
      if (!session) return;
      requireDatabase();
      const body = await readJson(req);
      const { documentType, data, recipientEmail } = body || {};
      if (!["fee-proposal", "service-agreement"].includes(documentType)) {
        return sendJson(res, 400, { error: "Unsupported document type." });
      }
      if (!data?.providerName || !Array.isArray(data?.services) || data.services.length === 0 || data.services.length > 250) {
        return sendJson(res, 400, { error: "Provider name and at least one service are required." });
      }

      const retentionResult = await pool.query("select inactive_invitation_days from retention_settings where id = 1");
      const inactiveRetentionDays = Number(retentionResult.rows[0]?.inactive_invitation_days || 365);
      const token = newInvitationToken();
      const hash = tokenHash(token);
      const originalDocumentHash = hashJson(data);
      const createdAt = new Date();
      const expiresAt = new Date(createdAt.getTime() + INVITATION_TTL_DAYS * 24 * 60 * 60 * 1000);
      const insertResult = await pool.query(
        `insert into provider_invitations (
          token_hash, document_type, status, recipient_email, payload, original_document_hash,
          created_at, expires_at, created_ip, created_user_agent, created_by_user_id, retention_expires_at
        ) values ($1,$2,'draft',$3,$4,$5,$6,$7,$8,$9,$10,$11)
        returning id`,
        [
          hash,
          documentType,
          recipientEmail || null,
          JSON.stringify(data),
          originalDocumentHash,
          createdAt.toISOString(),
          expiresAt.toISOString(),
          getClientIp(req),
          req.headers["user-agent"] || "unknown",
          session.user_id,
          new Date(createdAt.getTime() + inactiveRetentionDays * 24 * 60 * 60 * 1000).toISOString(),
        ],
      );
      await logInvitationEvent(insertResult.rows[0].id, "created", req, { documentType, originalDocumentHash, actorUserId: session.user_id });

      const providerPath = `/provider/${token}`;
      await logInvitationEvent(insertResult.rows[0].id, "link_created", req, {
        recipientEmail: recipientEmail || null,
      });
      return sendJson(res, 201, {
        invitationId: String(insertResult.rows[0].id),
        token,
        providerPath,
        createdAt: createdAt.toISOString(),
        expiresAt: expiresAt.toISOString(),
        status: "draft",
      });
    }

    const invitationMatch = url.pathname.match(/^\/api\/provider-invitations\/([^/]+)$/);
    if (req.method === "GET" && invitationMatch) {
      if (!allowRequest(req, "provider-invitation-view", 300)) {
        return sendJson(res, 429, { error: "Too many invitation requests. Please try again later." });
      }
      requireDatabase();
      const token = decodeURIComponent(invitationMatch[1]);
      const hash = tokenHash(token);
      const { rows } = await pool.query(
        `select id, document_type, status, payload, completed_payload, original_document_hash,
                created_at, expires_at, viewed_at, completed_at, approved_at, declined_at, decline_reason
         from provider_invitations where token_hash = $1`,
        [hash],
      );
      if (!rows.length) return sendJson(res, 404, { error: "Invitation not found." });
      const invite = rows[0];
      if (invite.status === "cancelled") return sendJson(res, 410, { error: "Invitation cancelled." });
      if (invite.status === "declined") return sendJson(res, 410, { status: "declined", error: "Invitation declined." });
      const expired = new Date(invite.expires_at).getTime() < Date.now() && ["draft", "sent", "viewed"].includes(invite.status);
      if (expired) {
        await pool.query(
          `update provider_invitations set status = 'expired',
             retention_expires_at = now() + make_interval(days => coalesce(
               (select inactive_invitation_days from retention_settings where id = 1), 365
             )),
             updated_at = now() where token_hash = $1`,
          [hash],
        );
        await logInvitationEvent(invite.id, "expired", req);
        return sendJson(res, 410, { error: "Invitation expired." });
      }
      if (["draft", "sent", "viewed"].includes(invite.status)) {
        await pool.query(
          `update provider_invitations set
             status = 'viewed', viewed_at = coalesce(viewed_at, now()),
             viewed_ip = $2, viewed_user_agent = $3, updated_at = now()
           where token_hash = $1`,
          [hash, getClientIp(req), req.headers["user-agent"] || "unknown"],
        );
        if (!invite.viewed_at) await logInvitationEvent(invite.id, "viewed", req);
      }
      return sendJson(res, 200, {
        documentType: invite.document_type,
        status: ["draft", "sent"].includes(invite.status) ? "viewed" : invite.status,
        data: invite.completed_payload || invite.payload,
        createdAt: invite.created_at,
        expiresAt: invite.expires_at,
        completedAt: invite.completed_at || undefined,
        approvedAt: invite.approved_at || undefined,
        originalDocumentHash: invite.original_document_hash || undefined,
        electronicRecordConsentText: ELECTRONIC_RECORD_CONSENT_TEXT,
      });
    }

    const providerFileMatch = url.pathname.match(/^\/api\/provider-invitations\/([^/]+)\/(document|certificate)$/);
    if (req.method === "GET" && providerFileMatch) {
      if (!allowRequest(req, "provider-completed-download", 60)) {
        return sendJson(res, 429, { error: "Too many download requests. Please try again later." });
      }
      requireDatabase();
      const token = decodeURIComponent(providerFileMatch[1]);
      const hash = tokenHash(token);
      const column = providerFileMatch[2] === "document" ? "pdf_bytes" : "certificate_bytes";
      const { rows } = await pool.query(
        `select id, status, ${column} as bytes,
                coalesce(completed_payload, payload)->>'documentNumber' as document_number
           from provider_invitations where token_hash = $1`,
        [hash],
      );
      if (!rows.length) return sendJson(res, 404, { error: "Invitation not found." });
      if (!["returned", "completed"].includes(rows[0].status) || !rows[0].bytes) {
        return sendJson(res, 409, { error: "The completed file is not available." });
      }
      await logInvitationEvent(rows[0].id, `provider_${providerFileMatch[2]}_downloaded`, req);
      return sendPdf(res, rows[0].bytes, `${rows[0].document_number || "provider-document"}-${providerFileMatch[2]}.pdf`);
    }

    const invitationDeclineMatch = url.pathname.match(/^\/api\/provider-invitations\/([^/]+)\/decline$/);
    if (req.method === "POST" && invitationDeclineMatch) {
      if (!allowRequest(req, "provider-invitation-decline", 12, 15 * 60 * 1000)) {
        return sendJson(res, 429, { error: "Too many response attempts. Please try again later." });
      }
      requireDatabase();
      const token = decodeURIComponent(invitationDeclineMatch[1]);
      const hash = tokenHash(token);
      const body = await readJson(req);
      const reason = limitedText(body?.reason, 1_000);
      const { rows } = await pool.query(
        "select id, status, expires_at from provider_invitations where token_hash = $1",
        [hash],
      );
      if (!rows.length) return sendJson(res, 404, { error: "Invitation not found." });
      if (["returned", "completed", "declined", "cancelled"].includes(rows[0].status)) {
        return sendJson(res, 409, { error: "This invitation can no longer be declined." });
      }
      if (new Date(rows[0].expires_at).getTime() < Date.now()) return sendJson(res, 410, { error: "Invitation expired." });
      const result = await pool.query(
        `update provider_invitations set status = 'declined', declined_at = now(), decline_reason = $2,
          retention_expires_at = now() + make_interval(days => coalesce(
            (select inactive_invitation_days from retention_settings where id = 1), 365
          )),
          updated_at = now() where token_hash = $1 and status in ('draft','sent','viewed') returning id, declined_at`,
        [hash, reason || null],
      );
      if (!result.rowCount) return sendJson(res, 409, { error: "This invitation can no longer be declined." });
      await logInvitationEvent(result.rows[0].id, "declined", req, { reason: reason || null });
      return sendJson(res, 200, { ok: true, status: "declined", declinedAt: result.rows[0].declined_at });
    }

    const invitationFinalizeMatch = url.pathname.match(/^\/api\/provider-invitations\/([^/]+)\/finalize$/);
    if (req.method === "POST" && invitationFinalizeMatch) {
      if (!allowRequest(req, "provider-invitation-finalize", 12, 15 * 60 * 1000)) {
        return sendJson(res, 429, { error: "Too many completion attempts. Please try again later." });
      }
      requireDatabase();
      const token = decodeURIComponent(invitationFinalizeMatch[1]);
      const hash = tokenHash(token);
      const body = await readJson(req);
      const { data, signedPdfBase64 } = body || {};
      if (!data?.providerSignerName || !data?.providerSignerTitle || !data?.agreedElectronic) {
        return sendJson(res, 400, { error: "Provider name, title, and electronic signature consent are required." });
      }
      if (data.providerSignatureType === "drawn" && !limitedText(data.providerSignatureData, 500_000).startsWith("data:image/png;base64,")) {
        return sendJson(res, 400, { error: "A valid drawn signature is required." });
      }
      if (!Array.isArray(data?.services) || !data.services.some((service) => service?.component)) {
        return sendJson(res, 400, { error: "At least one service is required." });
      }
      if (typeof signedPdfBase64 !== "string" || !signedPdfBase64 || signedPdfBase64.length > 25_000_000) {
        return sendJson(res, 413, { error: "The completed PDF is missing or too large." });
      }
      const { rows } = await pool.query(
        `select id, status, expires_at, created_at, viewed_at, payload, recipient_email,
                original_document_hash from provider_invitations where token_hash = $1`,
        [hash],
      );
      if (!rows.length) return sendJson(res, 404, { error: "Invitation not found." });
      if (["returned", "completed"].includes(rows[0].status)) return sendJson(res, 409, { error: "Invitation has already been submitted." });
      if (["declined", "cancelled"].includes(rows[0].status)) return sendJson(res, 410, { error: "Invitation is no longer active." });
      if (new Date(rows[0].expires_at).getTime() < Date.now()) return sendJson(res, 410, { error: "Invitation expired." });

      const pdfBytes = base64ToUint8(signedPdfBase64);
      if (Buffer.from(pdfBytes.subarray(0, 5)).toString("ascii") !== "%PDF-") {
        return sendJson(res, 400, { error: "The completed document is not a valid PDF." });
      }
      const pdfHash = sha256Hex(pdfBytes);
      const completedAt = new Date().toISOString();
      const completedData = buildCompletedProviderData(rows[0].payload, data, completedAt);
      if (!completedData.services.length) return sendJson(res, 400, { error: "At least one service is required." });
      if (!completedData.providerSignerName || !completedData.providerSignerTitle) {
        return sendJson(res, 400, { error: "Provider name and title are required." });
      }
      const ipAddress = getClientIp(req);
      const userAgent = req.headers["user-agent"] || "unknown";
      const signatureDataHash = sha256Hex(completedData.providerSignatureData || completedData.providerSignerName);
      const signatureHash = hashJson({
        signatureType: completedData.providerSignatureType,
        signatureDataHash,
        fullName: completedData.providerSignerName,
        ipAddress,
        originalDocumentHash: rows[0].original_document_hash,
      });
      const evidencePayload = {
        version: 1,
        invitationId: String(rows[0].id),
        documentNumber: completedData.documentNumber,
        originalDocumentHash: rows[0].original_document_hash,
        completedPayloadHash: hashJson(completedData),
        finalPdfHash: pdfHash,
        signatureType: completedData.providerSignatureType,
        signatureHash,
        signerName: completedData.providerSignerName,
        signerTitle: completedData.providerSignerTitle,
        ipAddress,
        userAgent,
        signedAt: completedAt,
        electronicRecordConsent: true,
        consentText: ELECTRONIC_RECORD_CONSENT_TEXT,
      };
      const evidenceHash = hashJson(evidencePayload);
      const requiresReview = providerChangedServiceTerms(rows[0].payload, completedData);
      const submissionStatus = requiresReview ? "returned" : "completed";
      const retentionResult = await pool.query("select completed_document_days from retention_settings where id = 1");
      const retentionExpiresAt = new Date(Date.now() + Number(retentionResult.rows[0]?.completed_document_days || DEFAULT_DOCUMENT_RETENTION_DAYS) * 24 * 60 * 60 * 1000).toISOString();
      const certificateBytes = await generateCertificatePdf({
        envelopeId: completedData.documentNumber,
        pdfHash,
        audit: {
          createdAt: new Date(rows[0].created_at).toISOString(),
          viewedAt: rows[0].viewed_at ? new Date(rows[0].viewed_at).toISOString() : completedAt,
          signedAt: completedAt,
          ipAddress,
          userAgent,
          occuMedRepName: completedData.preparedBy || "Occu-Med",
          clinicRepFullName: completedData.providerSignerName,
          agreedElectronic: true,
          originalDocumentHash: rows[0].original_document_hash,
          signatureType: completedData.providerSignatureType,
          signatureHash,
          evidenceHash,
          verificationUrl: FRONTEND_APP_URL ? `${FRONTEND_APP_URL}/verify` : undefined,
          consentText: ELECTRONIC_RECORD_CONSENT_TEXT,
          reviewStatus: requiresReview ? "Provider changes pending Occu-Med approval" : "Completed without provider term changes",
        },
      });
      const completionResult = await pool.query(
        `update provider_invitations set
           status = $14, completed_payload = $2, completed_at = $3,
           completed_ip = $4, completed_user_agent = $5,
           pdf_hash = $6, pdf_bytes = $7, certificate_bytes = $8,
           signature_hash = $9, evidence_hash = $10, evidence_payload = $11,
           consent_text = $12, signature_type = $13, retention_expires_at = $15, updated_at = now()
         where token_hash = $1 and status in ('draft','sent','viewed')
         returning id`,
        [
          hash,
          JSON.stringify(completedData),
          completedAt,
          ipAddress,
          userAgent,
          pdfHash,
          Buffer.from(pdfBytes),
          Buffer.from(certificateBytes),
          signatureHash,
          evidenceHash,
          JSON.stringify(evidencePayload),
          ELECTRONIC_RECORD_CONSENT_TEXT,
          completedData.providerSignatureType,
          submissionStatus,
          retentionExpiresAt,
        ],
      );
      if (!completionResult.rowCount) return sendJson(res, 409, { error: "Invitation has already been completed." });
      await logInvitationEvent(completionResult.rows[0].id, requiresReview ? "provider_changes_returned" : "completed", req, {
        pdfHash,
        signatureHash,
        evidenceHash,
        signatureType: completedData.providerSignatureType,
        requiresReview,
      });
      let emailSent = false;
      try {
        emailSent = requiresReview
          ? await maybeSendProviderChangesForReview({ data: completedData, pdfBytes, certificateBytes })
          : await maybeSendCompletedProviderDocument({
            data: completedData,
            recipientEmail: rows[0].recipient_email,
            pdfBytes,
            certificateBytes,
          });
      } catch (error) {
        console.error(requiresReview ? "provider-review email failed" : "completed provider document email failed", error);
      }
      return sendJson(res, 200, {
        ok: true,
        status: submissionStatus,
        requiresReview,
        completedAt,
        pdfHash,
        evidenceHash,
        pdfBase64: Buffer.from(pdfBytes).toString("base64"),
        certificateBase64: Buffer.from(certificateBytes).toString("base64"),
        emailSent,
      });
    }

    if (req.method === "POST" && url.pathname === "/api/signed/envelopes") {
      if (!allowRequest(req, "signed-envelope-create", 60)) {
        return sendJson(res, 429, { error: "Too many envelope requests. Please try again later." });
      }
      if (!await requireAdminAccess(req, res, "create_documents")) return;
      requireDatabase();
      const envelopeId = newEnvelopeId();
      const createdAt = new Date().toISOString();
      const ip = getClientIp(req);
      const userAgent = req.headers["user-agent"] || "unknown";

      await pool.query(
        "insert into envelopes (envelope_id, created_at, ip_address, user_agent, status) values ($1, $2, $3, $4, $5)",
        [envelopeId, createdAt, ip, userAgent, "created"]
      );

      return sendJson(res, 200, { envelopeId, createdAt });
    }

    const viewMatch = url.pathname.match(/^\/api\/signed\/envelopes\/([^/]+)\/view$/);
    if (req.method === "POST" && viewMatch) {
      if (!await requireAdminAccess(req, res, "create_documents")) return;
      const envelopeId = decodeURIComponent(viewMatch[1]);
      const viewedAt = new Date().toISOString();
      const ip = getClientIp(req);
      const ua = req.headers["user-agent"] || "unknown";

      await pool.query(
        `insert into envelopes (envelope_id, viewed_at, viewed_ip, viewed_user_agent, status, created_at, updated_at)
         values ($1, $2, $3, $4, $5, $2, now())
         on conflict (envelope_id) do update set
           viewed_at = excluded.viewed_at,
           viewed_ip = excluded.viewed_ip,
           viewed_user_agent = excluded.viewed_user_agent,
           status = excluded.status,
           updated_at = now()`,
        [envelopeId, viewedAt, ip, ua, "viewed"]
      );

      return sendJson(res, 200, { envelopeId, viewedAt });
    }

    const finalizeMatch = url.pathname.match(/^\/api\/signed\/envelopes\/([^/]+)\/finalize$/);
    if (req.method === "POST" && finalizeMatch) {
      if (!await requireAdminAccess(req, res, "create_documents")) return;
      const envelopeId = decodeURIComponent(finalizeMatch[1]);
      const body = await readJson(req);
      const { data, viewedAt, recipientEmail, signedPdfBase64 } = body;

      if (!data?.agreedElectronic) return sendJson(res, 400, { error: "Agreement required." });
      if (!data?.occuMedRepName || !data?.clinicRepFullName) {
        return sendJson(res, 400, { error: "Both signatures are required." });
      }

      const signedAt = new Date().toISOString();
      const existingEnvelope = await getEnvelope(envelopeId);
      const createdAt = existingEnvelope?.created_at || signedAt;
      const effectiveViewedAt = viewedAt || existingEnvelope?.viewed_at || signedAt;
      const ip = getClientIp(req);
      const userAgent = req.headers["user-agent"] || "unknown";

      const pdfBytes = signedPdfBase64
        ? base64ToUint8(signedPdfBase64)
        : await generateSignedPdf({ envelopeId, data, signedAt, viewedAt: effectiveViewedAt, ip, userAgent });

      const pdfHash = sha256Hex(pdfBytes);
      const certBytes = await generateCertificatePdf({
        envelopeId,
        pdfHash,
        audit: {
          createdAt,
          viewedAt: effectiveViewedAt,
          signedAt,
          ipAddress: ip,
          userAgent,
          occuMedRepName: data.occuMedRepName,
          clinicRepFullName: data.clinicRepFullName,
          agreedElectronic: Boolean(data.agreedElectronic),
        },
      });

      const pdfPath = `${envelopeId}/document.pdf`;
      const certPath = `${envelopeId}/certificate.pdf`;

      await pool.query(
        `insert into envelopes (
          envelope_id, status, pdf_hash, pdf_path, certificate_path,
          pdf_bytes, certificate_bytes,
          created_at, viewed_at, signed_at,
          ip_address, user_agent, signed_ip, signed_user_agent,
          occu_med_rep_name, occu_med_rep_title,
          clinic_rep_name, clinic_rep_title,
          agreed_electronic, recipient_email, payload, updated_at
        ) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,now())
        on conflict (envelope_id) do update set
          status = excluded.status,
          pdf_hash = excluded.pdf_hash,
          pdf_path = excluded.pdf_path,
          certificate_path = excluded.certificate_path,
          pdf_bytes = excluded.pdf_bytes,
          certificate_bytes = excluded.certificate_bytes,
          created_at = excluded.created_at,
          viewed_at = excluded.viewed_at,
          signed_at = excluded.signed_at,
          ip_address = excluded.ip_address,
          user_agent = excluded.user_agent,
          signed_ip = excluded.signed_ip,
          signed_user_agent = excluded.signed_user_agent,
          occu_med_rep_name = excluded.occu_med_rep_name,
          occu_med_rep_title = excluded.occu_med_rep_title,
          clinic_rep_name = excluded.clinic_rep_name,
          clinic_rep_title = excluded.clinic_rep_title,
          agreed_electronic = excluded.agreed_electronic,
          recipient_email = excluded.recipient_email,
          payload = excluded.payload,
          updated_at = now()`,
        [
          envelopeId, "signed", pdfHash, pdfPath, certPath,
          Buffer.from(pdfBytes), Buffer.from(certBytes),
          createdAt, effectiveViewedAt, signedAt,
          ip, userAgent, ip, userAgent,
          data.occuMedRepName, data.occuMedRepTitle,
          data.clinicRepFullName, data.clinicRepTitle,
          Boolean(data.agreedElectronic), recipientEmail || null,
          JSON.stringify(data),
        ]
      );

      await maybeSendEmail({ to: recipientEmail, envelopeId, pdfHash, pdfBytes, certBytes });

      return sendJson(res, 200, {
        envelopeId,
        signedAt,
        createdAt,
        viewedAt: effectiveViewedAt,
        ipAddress: ip,
        userAgent,
        pdfHash,
        pdfBase64: Buffer.from(pdfBytes).toString("base64"),
        certificateBase64: Buffer.from(certBytes).toString("base64"),
      });
    }

    if (req.method === "POST" && url.pathname === "/api/memos/send") {
      if (!await requireAdminAccess(req, res, "create_documents")) return;
      if (!allowRequest(req, "memo-send", 60)) {
        return sendJson(res, 429, { error: "Too many email requests. Please try again later." });
      }
      const body = await readJson(req);
      const { recipientEmail, subject, message, pdfBase64, filename } = body || {};
      if (!recipientEmail || !pdfBase64) return sendJson(res, 400, { error: "recipientEmail and pdfBase64 are required." });
      if (typeof pdfBase64 !== "string" || pdfBase64.length > 25_000_000) {
        return sendJson(res, 413, { error: "PDF payload too large. Please reduce file size and try again." });
      }
      const pdfBytes = base64ToUint8(pdfBase64);
      await sendMemoEmail({
        to: recipientEmail,
        subject: subject || "Occu-Med Memo",
        text: message || "Please find the attached memo.",
        pdfBytes,
        filename: filename || "memo.pdf",
      });
      return sendJson(res, 200, { ok: true });
    }

    return sendJson(res, 404, { error: "Not found" });
  } catch (error) {
    console.error("request failed", error);
    return sendJson(res, 500, { error: process.env.NODE_ENV === "production" ? "Internal server error." : String(error) });
  }
});

const port = Number(process.env.PORT || 3001);

async function start() {
  try {
    await initDbPool();
    await initDb();
  } catch (error) {
    console.error("database initialization failed:", error.message);
  }
  server.listen(port, () => {
    console.log(`occu-med backend listening on :${port}`);
  });
}

start();
